# coding: utf-8
"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from procurify_python_sdk.client_custom import ClientCustom
from procurify_python_sdk.configuration import Configuration
from procurify_python_sdk.api_client import ApiClient
from procurify_python_sdk.type_util import copy_signature
from procurify_python_sdk.apis.tags.account_codes_api import AccountCodesApi
from procurify_python_sdk.apis.tags.accounts_api import AccountsApi
from procurify_python_sdk.apis.tags.ap_api import ApApi
from procurify_python_sdk.apis.tags.catalog_api import CatalogApi
from procurify_python_sdk.apis.tags.currencies_api import CurrenciesApi
from procurify_python_sdk.apis.tags.custom_fields_api import CustomFieldsApi
from procurify_python_sdk.apis.tags.departments_api import DepartmentsApi
from procurify_python_sdk.apis.tags.locations_api import LocationsApi
from procurify_python_sdk.apis.tags.oauth_api import OauthApi
from procurify_python_sdk.apis.tags.order_items_api import OrderItemsApi
from procurify_python_sdk.apis.tags.permissions_api import PermissionsApi
from procurify_python_sdk.apis.tags.purchase_orders_api import PurchaseOrdersApi
from procurify_python_sdk.apis.tags.requisitions_api import RequisitionsApi
from procurify_python_sdk.apis.tags.users_api import UsersApi
from procurify_python_sdk.apis.tags.vendors_api import VendorsApi



class Procurify(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.account_codes: AccountCodesApi = AccountCodesApi(api_client)
        self.accounts: AccountsApi = AccountsApi(api_client)
        self.ap: ApApi = ApApi(api_client)
        self.catalog: CatalogApi = CatalogApi(api_client)
        self.currencies: CurrenciesApi = CurrenciesApi(api_client)
        self.custom_fields: CustomFieldsApi = CustomFieldsApi(api_client)
        self.departments: DepartmentsApi = DepartmentsApi(api_client)
        self.locations: LocationsApi = LocationsApi(api_client)
        self.oauth: OauthApi = OauthApi(api_client)
        self.order_items: OrderItemsApi = OrderItemsApi(api_client)
        self.permissions: PermissionsApi = PermissionsApi(api_client)
        self.purchase_orders: PurchaseOrdersApi = PurchaseOrdersApi(api_client)
        self.requisitions: RequisitionsApi = RequisitionsApi(api_client)
        self.users: UsersApi = UsersApi(api_client)
        self.vendors: VendorsApi = VendorsApi(api_client)
