# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from procurify_python_sdk.pydantic.ap_bill_payment_docs_nullable import APBillPaymentDocsNullable
from procurify_python_sdk.pydantic.approver_read import ApproverRead
from procurify_python_sdk.pydantic.approver_read_nullable import ApproverReadNullable
from procurify_python_sdk.pydantic.attachment import Attachment
from procurify_python_sdk.pydantic.bill_cost_read import BillCostRead
from procurify_python_sdk.pydantic.bill_purchase_order_docs import BillPurchaseOrderDocs
from procurify_python_sdk.pydantic.bill_status_enum import BillStatusEnum
from procurify_python_sdk.pydantic.bill_status_read import BillStatusRead
from procurify_python_sdk.pydantic.comment import Comment
from procurify_python_sdk.pydantic.currency import Currency
from procurify_python_sdk.pydantic.item_read_serializer_v2 import ItemReadSerializerV2
from procurify_python_sdk.pydantic.simple_user_summary import SimpleUserSummary
from procurify_python_sdk.pydantic.user_summary import UserSummary
from procurify_python_sdk.pydantic.vendor_read import VendorRead
from procurify_python_sdk.pydantic.version_choices_docs import VersionChoicesDocs
from procurify_python_sdk.pydantic.zero_one_two_enum import ZeroOneTwoEnum

class BillRead(BaseModel):
    uuid: str = Field(alias='uuid')

    user: UserSummary = Field(alias='user')

    vendor: VendorRead = Field(alias='vendor')

    items: typing.List[ItemReadSerializerV2] = Field(alias='items')

    costs: typing.List[BillCostRead] = Field(alias='costs')

    invoice_attachments: typing.List[Attachment] = Field(alias='invoice_attachments')

    bill_statuses: typing.List[BillStatusRead] = Field(alias='bill_statuses')

    currency: Currency = Field(alias='currency')

    version: typing.Optional[int] = Field(None, alias='version')

    id: typing.Optional[int] = Field(None, alias='id')

    approval_chain: typing.Optional[typing.Optional[int]] = Field(None, alias='approval_chain')

    approver: typing.Optional[ApproverReadNullable] = Field(None, alias='approver')

    comments: typing.Optional[typing.List[Comment]] = Field(None, alias='comments')

    version_choices: typing.Optional[typing.List[VersionChoicesDocs]] = Field(None, alias='version_choices')

    tax_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='tax_amount')

    inclusive_tax_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='inclusive_tax_amount')

    exclusive_tax_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='exclusive_tax_amount')

    subtotal_cost: typing.Optional[typing.Union[int, float]] = Field(None, alias='subtotal_cost')

    total_cost: typing.Optional[typing.Union[int, float]] = Field(None, alias='total_cost')

    total_cost_with_tax: typing.Optional[typing.Union[int, float]] = Field(None, alias='total_cost_with_tax')

    converted_total_cost: typing.Optional[typing.Union[int, float]] = Field(None, alias='converted_total_cost')

    next_approver_choices: typing.Optional[typing.Optional[typing.List[ApproverRead]]] = Field(None, alias='next_approver_choices')

    locked: typing.Optional[bool] = Field(None, alias='locked')

    bill_payment: typing.Optional[APBillPaymentDocsNullable] = Field(None, alias='bill_payment')

    creditcard: typing.Optional[int] = Field(None, alias='creditcard')

    creditcard_name: typing.Optional[str] = Field(None, alias='creditcard_name')

    last_export_user: typing.Optional[SimpleUserSummary] = Field(None, alias='last_export_user')

    last_export_date: typing.Optional[date] = Field(None, alias='last_export_date')

    vendor_name: typing.Optional[str] = Field(None, alias='vendor_name')

    vendor_contact: typing.Optional[str] = Field(None, alias='vendor_contact')

    vendor_address_one: typing.Optional[str] = Field(None, alias='vendor_address_one')

    vendor_address_two: typing.Optional[str] = Field(None, alias='vendor_address_two')

    vendor_postal_code: typing.Optional[str] = Field(None, alias='vendor_postal_code')

    vendor_city: typing.Optional[str] = Field(None, alias='vendor_city')

    vendor_state_province: typing.Optional[str] = Field(None, alias='vendor_state_province')

    vendor_country: typing.Optional[str] = Field(None, alias='vendor_country')

    last_modified_datetime: typing.Optional[datetime] = Field(None, alias='last_modified_datetime')

    submitted_date: typing.Optional[typing.Optional[datetime]] = Field(None, alias='submitted_date')

    invoice_number: typing.Optional[str] = Field(None, alias='invoice_number')

    invoice_date: typing.Optional[typing.Optional[datetime]] = Field(None, alias='invoice_date')

    due_date: typing.Optional[typing.Optional[datetime]] = Field(None, alias='due_date')

    payment_terms: typing.Optional[str] = Field(None, alias='payment_terms')

    status: typing.Optional[BillStatusEnum] = Field(None, alias='status')

    type: typing.Optional[ZeroOneTwoEnum] = Field(None, alias='type')

    active: typing.Optional[bool] = Field(None, alias='active')

    note: typing.Optional[str] = Field(None, alias='note')

    gl_post_date: typing.Optional[typing.Optional[datetime]] = Field(None, alias='gl_post_date')

    group: typing.Optional[typing.Optional[int]] = Field(None, alias='group')

    payment_method: typing.Optional[typing.Optional[int]] = Field(None, alias='payment_method')

    payment_method_name: typing.Optional[str] = Field(None, alias='payment_method_name')

    added_purchase_orders: typing.Optional[typing.List[BillPurchaseOrderDocs]] = Field(None, alias='added_purchase_orders')

    shipping_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='shipping_amount')

    invoice_uuid: typing.Optional[str] = Field(None, alias='invoice_uuid')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
