# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from procurify_python_sdk.pydantic.account_code_read import AccountCodeRead
from procurify_python_sdk.pydantic.catalog_item_read_departments import CatalogItemReadDepartments
from procurify_python_sdk.pydantic.catalog_item_read_selected_account import CatalogItemReadSelectedAccount
from procurify_python_sdk.pydantic.currency_summary import CurrencySummary
from procurify_python_sdk.pydantic.custom_field_value_read import CustomFieldValueRead
from procurify_python_sdk.pydantic.vendor_read import VendorRead

class CatalogItemRead(BaseModel):
    name: str = Field(alias='name')

    pref_vendor: VendorRead = Field(alias='pref_vendor')

    account_code: AccountCodeRead = Field(alias='account_code')

    currency: CurrencySummary = Field(alias='currency')

    description: typing.Optional[typing.Optional[str]] = Field(None, alias='description')

    id: typing.Optional[int] = Field(None, alias='id')

    image: typing.Optional[str] = Field(None, alias='image')

    unit_type: typing.Optional[str] = Field(None, alias='unitType')

    internal_s_k_u: typing.Optional[str] = Field(None, alias='internalSKU')

    product_url: typing.Optional[typing.Optional[str]] = Field(None, alias='product_url')

    price: typing.Optional[str] = Field(None, alias='price')

    rfo_lock: typing.Optional[bool] = Field(None, alias='rfo_lock')

    departments: typing.Optional[CatalogItemReadDepartments] = Field(None, alias='departments')

    custom_fields: typing.Optional[typing.List[CustomFieldValueRead]] = Field(None, alias='custom_fields')

    requested_count: typing.Optional[int] = Field(None, alias='requested_count')

    last_requested_date: typing.Optional[typing.Optional[datetime]] = Field(None, alias='last_requested_date')

    selected_account: typing.Optional[CatalogItemReadSelectedAccount] = Field(None, alias='selected_account')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
