# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from procurify_python_sdk.pydantic.attachment import Attachment
from procurify_python_sdk.pydantic.cost_allocation_read import CostAllocationRead
from procurify_python_sdk.pydantic.credit_card_item_read_nullable import CreditCardItemReadNullable
from procurify_python_sdk.pydantic.currency import Currency
from procurify_python_sdk.pydantic.custom_field_value_read import CustomFieldValueRead
from procurify_python_sdk.pydantic.expense_read_nullable import ExpenseReadNullable
from procurify_python_sdk.pydantic.expense_report_docs import ExpenseReportDocs
from procurify_python_sdk.pydantic.order_item_read import OrderItemRead
from procurify_python_sdk.pydantic.po_docs import PODocs
from procurify_python_sdk.pydantic.unit_cost_diff_log_docs_nullable import UnitCostDiffLogDocsNullable
from procurify_python_sdk.pydantic.vendor_read import VendorRead

class ItemReadSerializerV2(BaseModel):
    description: str = Field(alias='description')

    expense: ExpenseReadNullable = Field(alias='expense')

    vendor: VendorRead = Field(alias='vendor')

    quantity: str = Field(alias='quantity')

    currency: Currency = Field(alias='currency')

    cost_allocations: typing.List[CostAllocationRead] = Field(alias='cost_allocations')

    creditcard_item: CreditCardItemReadNullable = Field(alias='creditcard_item')

    id: typing.Optional[int] = Field(None, alias='id')

    orderitem: typing.Optional[OrderItemRead] = Field(None, alias='orderitem')

    bill: typing.Optional[typing.Optional[int]] = Field(None, alias='bill')

    sku: typing.Optional[str] = Field(None, alias='sku')

    po: typing.Optional[PODocs] = Field(None, alias='po')

    unit: typing.Optional[str] = Field(None, alias='unit')

    total_cost: typing.Optional[typing.Union[int, float]] = Field(None, alias='total_cost')

    received_on: typing.Optional[datetime] = Field(None, alias='received_on')

    packing_slips: typing.Optional[typing.List[Attachment]] = Field(None, alias='packing_slips')

    archived: typing.Optional[bool] = Field(None, alias='archived')

    expense_report: typing.Optional[ExpenseReportDocs] = Field(None, alias='expense_report')

    same_unit_cost: typing.Optional[bool] = Field(None, alias='same_unit_cost')

    is_edited: typing.Optional[bool] = Field(None, alias='is_edited')

    unit_cost_diff_log: typing.Optional[UnitCostDiffLogDocsNullable] = Field(None, alias='unit_cost_diff_log')

    tax_name: typing.Optional[str] = Field(None, alias='tax_name')

    tax_percentage: typing.Optional[typing.Optional[str]] = Field(None, alias='tax_percentage')

    tax_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='tax_amount')

    tax_is_inclusive: typing.Optional[bool] = Field(None, alias='tax_is_inclusive')

    tax: typing.Optional[typing.Optional[int]] = Field(None, alias='tax')

    total_cost_with_tax: typing.Optional[typing.Union[int, float]] = Field(None, alias='total_cost_with_tax')

    shipping_amount: typing.Optional[typing.Optional[str]] = Field(None, alias='shipping_amount')

    unit_cost: typing.Optional[typing.Union[int, float]] = Field(None, alias='unit_cost')

    custom_fields: typing.Optional[typing.List[CustomFieldValueRead]] = Field(None, alias='custom_fields')

    item_type: typing.Optional[int] = Field(None, alias='item_type')

    type: typing.Optional[str] = Field(None, alias='type')

    bill_by_cost: typing.Optional[bool] = Field(None, alias='bill_by_cost')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
