# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from procurify_python_sdk.pydantic.blanket_order_item_read import BlanketOrderItemRead
from procurify_python_sdk.pydantic.null_enum import NullEnum
from procurify_python_sdk.pydantic.order_item_item_attachments import OrderItemItemAttachments
from procurify_python_sdk.pydantic.order_item_po import OrderItemPo
from procurify_python_sdk.pydantic.order_item_status_enum import OrderItemStatusEnum
from procurify_python_sdk.pydantic.zero_one_enum import ZeroOneEnum
from procurify_python_sdk.pydantic.zero_one_two_enum import ZeroOneTwoEnum

class OrderItem(BaseModel):
    account: int = Field(alias='account')

    approved_datetime: typing.Optional[datetime] = Field(alias='approved_datetime')

    currency: int = Field(alias='currency')

    name: str = Field(alias='name')

    num: str = Field(alias='num')

    pref_vendor: int = Field(alias='pref_vendor')

    price: str = Field(alias='price')

    quantity: str = Field(alias='quantity')

    unit: str = Field(alias='unit')

    p_o: typing.Optional[OrderItemPo] = Field(None, alias='PO')

    p_o_line_num: typing.Optional[int] = Field(None, alias='PO_line_num')

    account_code: typing.Optional[str] = Field(None, alias='accountCode')

    active: typing.Optional[bool] = Field(None, alias='active')

    approved_currency_rate: typing.Optional[typing.Optional[str]] = Field(None, alias='approved_currency_rate')

    approved_price: typing.Optional[typing.Optional[str]] = Field(None, alias='approved_price')

    approved_quantity: typing.Optional[typing.Optional[str]] = Field(None, alias='approved_quantity')

    approved_shipping_amount: typing.Optional[typing.Optional[str]] = Field(None, alias='approved_shipping_amount')

    approved_tax_amount: typing.Optional[typing.Optional[str]] = Field(None, alias='approved_tax_amount')

    attachments: typing.Optional[str] = Field(None, alias='attachments')

    catalog_item: typing.Optional[typing.Optional[int]] = Field(None, alias='catalog_item')

    created_at: typing.Optional[datetime] = Field(None, alias='created_at')

    date_invoiced: typing.Optional[typing.Optional[datetime]] = Field(None, alias='dateInvoiced')

    # External id of the order item
    external_id: typing.Optional[str] = Field(None, alias='external_id')

    hot: typing.Optional[bool] = Field(None, alias='hot')

    id: typing.Optional[int] = Field(None, alias='id')

    inventory_item: typing.Optional[typing.Optional[int]] = Field(None, alias='inventoryItem')

    is_active: typing.Optional[bool] = Field(None, alias='is_active')

    item_attachments: typing.Optional[OrderItemItemAttachments] = Field(None, alias='item_attachments')

    last_changed_by: typing.Optional[typing.Optional[int]] = Field(None, alias='last_changed_by')

    last_modified: typing.Optional[datetime] = Field(None, alias='last_modified')

    line_comment: typing.Optional[typing.Optional[str]] = Field(None, alias='lineComment')

    order_num: typing.Optional[typing.Optional[int]] = Field(None, alias='orderNum')

    po_note: typing.Optional[str] = Field(None, alias='po_note')

    po_version: typing.Optional[int] = Field(None, alias='po_version')

    purchase_order: typing.Optional[typing.Optional[int]] = Field(None, alias='purchase_order')

    purchaser: typing.Optional[typing.Optional[int]] = Field(None, alias='purchaser')

    received_fail_qty: typing.Optional[str] = Field(None, alias='receivedFailQty')

    received_pass_qty: typing.Optional[str] = Field(None, alias='receivedPassQty')

    shipping_amount: typing.Optional[typing.Optional[str]] = Field(None, alias='shipping_amount')

    sku: typing.Optional[str] = Field(None, alias='sku')

    status: typing.Optional[typing.Union[OrderItemStatusEnum, NullEnum]] = Field(None, alias='status')

    tax_amount: typing.Optional[typing.Optional[str]] = Field(None, alias='tax_amount')

    total_cost: typing.Optional[str] = Field(None, alias='total_cost')

    updated_at: typing.Optional[datetime] = Field(None, alias='updated_at')

    vendor: typing.Optional[typing.Optional[str]] = Field(None, alias='vendor')

    receive_method: typing.Optional[ZeroOneEnum] = Field(None, alias='receive_method')

    type: typing.Optional[ZeroOneTwoEnum] = Field(None, alias='type')

    blanket: typing.Optional[BlanketOrderItemRead] = Field(None, alias='blanket')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
