# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from procurify_python_sdk.pydantic.account_read import AccountRead
from procurify_python_sdk.pydantic.adjustment import Adjustment
from procurify_python_sdk.pydantic.allocation_read import AllocationRead
from procurify_python_sdk.pydantic.attachment import Attachment
from procurify_python_sdk.pydantic.blanket_order_item_read import BlanketOrderItemRead
from procurify_python_sdk.pydantic.catalog_item_read_nullable import CatalogItemReadNullable
from procurify_python_sdk.pydantic.comment import Comment
from procurify_python_sdk.pydantic.cost_details_nullable import CostDetailsNullable
from procurify_python_sdk.pydantic.currency_summary import CurrencySummary
from procurify_python_sdk.pydantic.custom_field_value_read import CustomFieldValueRead
from procurify_python_sdk.pydantic.master_logger import MasterLogger
from procurify_python_sdk.pydantic.null_enum import NullEnum
from procurify_python_sdk.pydantic.order_item_read_po import OrderItemReadPo
from procurify_python_sdk.pydantic.order_item_status_enum import OrderItemStatusEnum
from procurify_python_sdk.pydantic.recurring_order_item_nullable import RecurringOrderItemNullable
from procurify_python_sdk.pydantic.simple_user_summary import SimpleUserSummary
from procurify_python_sdk.pydantic.user_summary import UserSummary
from procurify_python_sdk.pydantic.vendor_read import VendorRead
from procurify_python_sdk.pydantic.zero_one_enum import ZeroOneEnum
from procurify_python_sdk.pydantic.zero_one_two_enum import ZeroOneTwoEnum

class OrderItemRead(BaseModel):
    account: AccountRead = Field(alias='account')

    approved_datetime: typing.Optional[datetime] = Field(alias='approved_datetime')

    approved_quantity: typing.Union[int, float] = Field(alias='approved_quantity')

    catalog_item: CatalogItemReadNullable = Field(alias='catalog_item')

    currency: CurrencySummary = Field(alias='currency')

    item_attachments: typing.List[Attachment] = Field(alias='item_attachments')

    name: str = Field(alias='name')

    num: str = Field(alias='num')

    pref_vendor: VendorRead = Field(alias='pref_vendor')

    price: str = Field(alias='price')

    purchaser: UserSummary = Field(alias='purchaser')

    quantity: typing.Union[int, float] = Field(alias='quantity')

    received_fail_qty: typing.Union[int, float] = Field(alias='receivedFailQty')

    received_pass_qty: typing.Union[int, float] = Field(alias='receivedPassQty')

    unit: str = Field(alias='unit')

    recurrence: RecurringOrderItemNullable = Field(alias='recurrence')

    p_o: typing.Optional[OrderItemReadPo] = Field(None, alias='PO')

    p_o_line_num: typing.Optional[int] = Field(None, alias='PO_line_num')

    account_code: typing.Optional[str] = Field(None, alias='accountCode')

    active: typing.Optional[bool] = Field(None, alias='active')

    approved_currency_rate: typing.Optional[typing.Optional[str]] = Field(None, alias='approved_currency_rate')

    approved_price: typing.Optional[typing.Optional[str]] = Field(None, alias='approved_price')

    approved_shipping_amount: typing.Optional[typing.Optional[str]] = Field(None, alias='approved_shipping_amount')

    approved_tax_amount: typing.Optional[typing.Optional[str]] = Field(None, alias='approved_tax_amount')

    attachments: typing.Optional[str] = Field(None, alias='attachments')

    created_at: typing.Optional[datetime] = Field(None, alias='created_at')

    date_invoiced: typing.Optional[typing.Optional[datetime]] = Field(None, alias='dateInvoiced')

    # External id of the order item
    external_id: typing.Optional[str] = Field(None, alias='external_id')

    hot: typing.Optional[bool] = Field(None, alias='hot')

    id: typing.Optional[int] = Field(None, alias='id')

    inventory_item: typing.Optional[typing.Optional[int]] = Field(None, alias='inventoryItem')

    is_active: typing.Optional[bool] = Field(None, alias='is_active')

    last_changed_by: typing.Optional[typing.Optional[int]] = Field(None, alias='last_changed_by')

    last_modified: typing.Optional[datetime] = Field(None, alias='last_modified')

    line_comment: typing.Optional[typing.Optional[str]] = Field(None, alias='lineComment')

    order_num: typing.Optional[typing.Optional[int]] = Field(None, alias='orderNum')

    po_note: typing.Optional[str] = Field(None, alias='po_note')

    po_version: typing.Optional[int] = Field(None, alias='po_version')

    purchase_order: typing.Optional[typing.Optional[int]] = Field(None, alias='purchase_order')

    shipping_amount: typing.Optional[typing.Optional[str]] = Field(None, alias='shipping_amount')

    sku: typing.Optional[str] = Field(None, alias='sku')

    status: typing.Optional[typing.Union[OrderItemStatusEnum, NullEnum]] = Field(None, alias='status')

    tax_amount: typing.Optional[typing.Optional[str]] = Field(None, alias='tax_amount')

    total_cost: typing.Optional[str] = Field(None, alias='total_cost')

    updated_at: typing.Optional[datetime] = Field(None, alias='updated_at')

    vendor: typing.Optional[str] = Field(None, alias='vendor')

    receive_method: typing.Optional[ZeroOneEnum] = Field(None, alias='receive_method')

    type: typing.Optional[ZeroOneTwoEnum] = Field(None, alias='type')

    blanket: typing.Optional[BlanketOrderItemRead] = Field(None, alias='blanket')

    comments: typing.Optional[typing.List[Comment]] = Field(None, alias='comments')

    confirmation_status: typing.Optional[typing.Optional[int]] = Field(None, alias='confirmation_status')

    confirmation_status_description: typing.Optional[typing.Optional[str]] = Field(None, alias='confirmation_status_description')

    cost_details: typing.Optional[CostDetailsNullable] = Field(None, alias='cost_details')

    custom_fields: typing.Optional[typing.List[CustomFieldValueRead]] = Field(None, alias='custom_fields')

    date_required: typing.Optional[datetime] = Field(None, alias='date_required')

    has_sibling_items: typing.Optional[bool] = Field(None, alias='has_sibling_items')

    line_comment: typing.Optional[str] = Field(None, alias='line_comment')

    logs: typing.Optional[typing.List[MasterLogger]] = Field(None, alias='logs')

    order_description: typing.Optional[str] = Field(None, alias='order_description')

    order_status: typing.Optional[int] = Field(None, alias='order_status')

    order_uuid: typing.Optional[str] = Field(None, alias='order_uuid')

    punchout_supplier_icon: typing.Optional[typing.Optional[str]] = Field(None, alias='punchout_supplier_icon')

    punchout_supplier_name: typing.Optional[typing.Optional[str]] = Field(None, alias='punchout_supplier_name')

    punchout_system: typing.Optional[typing.Optional[int]] = Field(None, alias='punchout_system')

    punchout_vendor_reference: typing.Optional[typing.Optional[int]] = Field(None, alias='punchout_vendor_reference')

    punchout_supplier_can_update_quantity: typing.Optional[bool] = Field(None, alias='punchout_supplier_can_update_quantity')

    purchase_order_number: typing.Optional[str] = Field(None, alias='purchase_order_number')

    purchase_order_uuid: typing.Optional[str] = Field(None, alias='purchase_order_uuid')

    purchased_currency_rate: typing.Optional[str] = Field(None, alias='purchased_currency_rate')

    requester: typing.Optional[SimpleUserSummary] = Field(None, alias='requester')

    spend_allocation: typing.Optional[typing.List[AllocationRead]] = Field(None, alias='spend_allocation')

    submitted_date: typing.Optional[datetime] = Field(None, alias='submitted_date')

    taxes: typing.Optional[typing.Optional[typing.List[Adjustment]]] = Field(None, alias='taxes')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
