# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from procurify_python_sdk.paths.api_v2_ap_bills_id.get import BillsGetById
from procurify_python_sdk.paths.api_v3_ap_bills.get import BillsList
from procurify_python_sdk.paths.api_v2_ap_company_payment_methods.get import CompanyPaymentMethodsList
from procurify_python_sdk.paths.api_v2_ap_company_payment_methods.post import CreateCompanyPaymentMethod
from procurify_python_sdk.paths.api_v2_ap_vendor_payment_methods.post import CreateVendorPaymentMethod
from procurify_python_sdk.paths.api_v2_ap_payments.get import GetPayments
from procurify_python_sdk.paths.api_v2_ap_items.get import ItemsGet
from procurify_python_sdk.paths.api_v2_ap_payments_id_approver_choices.get import PaymentsApproverChoicesRetrieve
from procurify_python_sdk.paths.api_v2_ap_vendor_payment_methods.get import VendorPaymentMethodsList
from procurify_python_sdk.apis.tags.ap_api_raw import ApApiRaw


class ApApi(
    BillsGetById,
    BillsList,
    CompanyPaymentMethodsList,
    CreateCompanyPaymentMethod,
    CreateVendorPaymentMethod,
    GetPayments,
    ItemsGet,
    PaymentsApproverChoicesRetrieve,
    VendorPaymentMethodsList,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ApApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ApApiRaw(api_client)
