# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from procurify_python_sdk.type.ap_bill_payment_docs_nullable import APBillPaymentDocsNullable
from procurify_python_sdk.type.approver_read import ApproverRead
from procurify_python_sdk.type.approver_read_nullable import ApproverReadNullable
from procurify_python_sdk.type.attachment import Attachment
from procurify_python_sdk.type.bill_cost_read import BillCostRead
from procurify_python_sdk.type.bill_purchase_order_docs import BillPurchaseOrderDocs
from procurify_python_sdk.type.bill_status_enum import BillStatusEnum
from procurify_python_sdk.type.bill_status_read import BillStatusRead
from procurify_python_sdk.type.comment import Comment
from procurify_python_sdk.type.currency import Currency
from procurify_python_sdk.type.item_read_serializer_v2 import ItemReadSerializerV2
from procurify_python_sdk.type.simple_user_summary import SimpleUserSummary
from procurify_python_sdk.type.user_summary import UserSummary
from procurify_python_sdk.type.vendor_read import VendorRead
from procurify_python_sdk.type.version_choices_docs import VersionChoicesDocs
from procurify_python_sdk.type.zero_one_two_enum import ZeroOneTwoEnum

class RequiredBillRead(TypedDict):
    uuid: str

    user: UserSummary

    vendor: VendorRead

    items: typing.List[ItemReadSerializerV2]

    costs: typing.List[BillCostRead]

    invoice_attachments: typing.List[Attachment]

    bill_statuses: typing.List[BillStatusRead]

    currency: Currency

class OptionalBillRead(TypedDict, total=False):
    version: int

    id: int

    approval_chain: typing.Optional[int]

    approver: typing.Optional[ApproverReadNullable]

    comments: typing.List[Comment]

    version_choices: typing.List[VersionChoicesDocs]

    tax_amount: typing.Union[int, float]

    inclusive_tax_amount: typing.Union[int, float]

    exclusive_tax_amount: typing.Union[int, float]

    subtotal_cost: typing.Union[int, float]

    total_cost: typing.Union[int, float]

    total_cost_with_tax: typing.Union[int, float]

    converted_total_cost: typing.Union[int, float]

    next_approver_choices: typing.Optional[typing.List[ApproverRead]]

    locked: bool

    bill_payment: typing.Optional[APBillPaymentDocsNullable]

    creditcard: int

    creditcard_name: str

    last_export_user: SimpleUserSummary

    last_export_date: date

    vendor_name: str

    vendor_contact: str

    vendor_address_one: str

    vendor_address_two: str

    vendor_postal_code: str

    vendor_city: str

    vendor_state_province: str

    vendor_country: str

    last_modified_datetime: datetime

    submitted_date: typing.Optional[datetime]

    invoice_number: str

    invoice_date: typing.Optional[datetime]

    due_date: typing.Optional[datetime]

    payment_terms: str

    status: BillStatusEnum

    type: ZeroOneTwoEnum

    active: bool

    note: str

    gl_post_date: typing.Optional[datetime]

    group: typing.Optional[int]

    payment_method: typing.Optional[int]

    payment_method_name: str

    added_purchase_orders: typing.List[BillPurchaseOrderDocs]

    shipping_amount: typing.Union[int, float]

    invoice_uuid: str

class BillRead(RequiredBillRead, OptionalBillRead):
    pass
