# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from procurify_python_sdk.type.blank_enum import BlankEnum
from procurify_python_sdk.type.language_enum import LanguageEnum
from procurify_python_sdk.type.location_timezone_enum import LocationTimezoneEnum
from procurify_python_sdk.type.null_enum import NullEnum
from procurify_python_sdk.type.setup_stage_enum import SetupStageEnum

class RequiredBranch(TypedDict):
    name: str

    phoneOne: str

    localCurrency: int

class OptionalBranch(TypedDict, total=False):
    id: int

    # External id
    external_id: typing.Optional[str]

    url: typing.Optional[str]

    logo: str

    language: LanguageEnum

    multipleLocations: bool

    locationTimezone: typing.Union[LocationTimezoneEnum, BlankEnum, NullEnum]

    userLimit: int

    budgetOvertureToggle: bool

    purchase_filtering: bool

    catalog_permission: bool

    separate_expense_approval: bool

    standalone_travel_approval: bool

    phoneTwo: typing.Optional[str]

    fax: typing.Optional[str]

    email: typing.Optional[str]

    fiscalYearEndDay: typing.Optional[int]

    fiscalYearEndMonth: typing.Optional[int]

    beginDate: datetime

    ported: bool

    port_date: typing.Optional[datetime]

    active: bool

    activated: bool

    setup_stage: SetupStageEnum

    contactPerson: typing.Optional[int]

    buyerAddress: typing.Optional[int]

    shippingAddress: typing.Optional[int]

class Branch(RequiredBranch, OptionalBranch):
    pass
