# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from procurify_python_sdk.type.credit_card import CreditCard
from procurify_python_sdk.type.nested_vendor_request import NestedVendorRequest
from procurify_python_sdk.type.optimized_vendor_email import OptimizedVendorEmail
from procurify_python_sdk.type.payment_method_nullable import PaymentMethodNullable
from procurify_python_sdk.type.payment_method_read import PaymentMethodRead
from procurify_python_sdk.type.payment_term_nullable import PaymentTermNullable
from procurify_python_sdk.type.shipping_method_nullable import ShippingMethodNullable
from procurify_python_sdk.type.shipping_term_nullable import ShippingTermNullable
from procurify_python_sdk.type.vendor_type_enum import VendorTypeEnum

class RequiredOptimizedVendor(TypedDict):
    # Name of the vendor
    name: str

    email: OptimizedVendorEmail

    type: VendorTypeEnum

    overall_score: typing.Optional[str]

class OptionalOptimizedVendor(TypedDict, total=False):
    id: int

    active: bool

    # First line of address
    addressLineOne: typing.Optional[str]

    # Second line of address
    addressLineTwo: typing.Optional[str]

    # Postal or Zip code of the vendor
    postalCode: typing.Optional[str]

    # City of the vendor
    city: typing.Optional[str]

    # State or Province of the vendor
    state_province: typing.Optional[str]

    # Country of the vendor
    country: typing.Optional[str]

    # Primary phone no. of the vendor
    phoneOne: typing.Optional[str]

    # Secondary phone no. of the vendor
    phoneTwo: typing.Optional[str]

    # Fax no. of the vendor
    fax: typing.Optional[str]

    # Notes about the vendor
    comments: typing.Optional[str]

    # Contact person of the vendor
    contact: typing.Optional[str]

    # Website of the vendor
    url: typing.Optional[str]

    # External id of the vendor
    external_id: typing.Optional[str]

    dateModified: datetime

    currency: typing.Optional[int]

    payment_term_ref: typing.Optional[PaymentTermNullable]

    shipping_term_ref: typing.Optional[ShippingTermNullable]

    payment_method_ref: typing.Optional[PaymentMethodNullable]

    shipping_method_ref: typing.Optional[ShippingMethodNullable]

    payment_methods: typing.List[PaymentMethodRead]

    tax: typing.Optional[int]

    default_payment_method: typing.Optional[int]

    creditcards: typing.List[CreditCard]

    is_1099_eligible: typing.Optional[bool]

    is_auto_email_po_enabled: bool

    # Placeholder for a KVStore value
    po_pdf_labels: str

    vendor_request: NestedVendorRequest

class OptimizedVendor(RequiredOptimizedVendor, OptionalOptimizedVendor):
    pass
