# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from procurify_python_sdk.type.blanket_order_item_read import BlanketOrderItemRead
from procurify_python_sdk.type.null_enum import NullEnum
from procurify_python_sdk.type.order_item_item_attachments import OrderItemItemAttachments
from procurify_python_sdk.type.order_item_po import OrderItemPo
from procurify_python_sdk.type.order_item_status_enum import OrderItemStatusEnum
from procurify_python_sdk.type.zero_one_enum import ZeroOneEnum
from procurify_python_sdk.type.zero_one_two_enum import ZeroOneTwoEnum

class RequiredOrderItem(TypedDict):
    account: int

    approved_datetime: typing.Optional[datetime]

    currency: int

    name: str

    num: str

    pref_vendor: int

    price: str

    quantity: str

    unit: str

class OptionalOrderItem(TypedDict, total=False):
    PO: OrderItemPo

    PO_line_num: int

    accountCode: str

    active: bool

    approved_currency_rate: typing.Optional[str]

    approved_price: typing.Optional[str]

    approved_quantity: typing.Optional[str]

    approved_shipping_amount: typing.Optional[str]

    approved_tax_amount: typing.Optional[str]

    attachments: str

    catalog_item: typing.Optional[int]

    created_at: datetime

    dateInvoiced: typing.Optional[datetime]

    # External id of the order item
    external_id: str

    hot: bool

    id: int

    inventoryItem: typing.Optional[int]

    is_active: bool

    item_attachments: OrderItemItemAttachments

    last_changed_by: typing.Optional[int]

    last_modified: datetime

    lineComment: typing.Optional[str]

    orderNum: typing.Optional[int]

    po_note: str

    po_version: int

    purchase_order: typing.Optional[int]

    purchaser: typing.Optional[int]

    receivedFailQty: str

    receivedPassQty: str

    shipping_amount: typing.Optional[str]

    sku: str

    status: typing.Union[OrderItemStatusEnum, NullEnum]

    tax_amount: typing.Optional[str]

    total_cost: str

    updated_at: datetime

    vendor: typing.Optional[str]

    receive_method: ZeroOneEnum

    type: ZeroOneTwoEnum

    blanket: BlanketOrderItemRead

class OrderItem(RequiredOrderItem, OptionalOrderItem):
    pass
