# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from procurify_python_sdk.type.address_docs_nullable import AddressDocsNullable
from procurify_python_sdk.type.branch import Branch
from procurify_python_sdk.type.currency_summary import CurrencySummary
from procurify_python_sdk.type.department_summary import DepartmentSummary
from procurify_python_sdk.type.master_logger import MasterLogger
from procurify_python_sdk.type.order_status_enum import OrderStatusEnum
from procurify_python_sdk.type.punch_out_read_docs_nullable import PunchOutReadDocsNullable
from procurify_python_sdk.type.user_summary import UserSummary

class RequiredOrderRead(TypedDict):
    uuid: str

    branch: Branch

    user: UserSummary

    department: DepartmentSummary

    logs: typing.List[MasterLogger]

    dateRequired: datetime

    next_approver: UserSummary

class OptionalOrderRead(TypedDict, total=False):
    description: typing.Optional[str]

    num: int

    currency: CurrencySummary

    total_cost_in_base_currency: typing.Union[int, float]

    item_count: int

    ip_address: typing.Optional[str]

    date: datetime

    dateModified: datetime

    lineCount: typing.Optional[int]

    purchasedCount: int

    totalPrice: typing.Optional[str]

    status: OrderStatusEnum

    approval_delegatee: typing.Optional[int]

    punchout_group: typing.Optional[PunchOutReadDocsNullable]

    punchout_shipping_address: typing.Optional[AddressDocsNullable]

    punchout_items_rejected: bool

    punchout_supplier_name: typing.Optional[str]

    punchout_supplier_icon: typing.Optional[str]

    punchout_vendor_reference: typing.Optional[int]

    has_blanket_order_items: bool

class OrderRead(RequiredOrderRead, OptionalOrderRead):
    pass
