# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from procurify_python_sdk.type.expense_type_enum_nullable import ExpenseTypeEnumNullable
from procurify_python_sdk.type.fulfilment_status_enum import FulfilmentStatusEnum
from procurify_python_sdk.type.null_enum import NullEnum
from procurify_python_sdk.type.price_modifier_docs import PriceModifierDocs
from procurify_python_sdk.type.purchase_order_state_enum import PurchaseOrderStateEnum
from procurify_python_sdk.type.simple_currency import SimpleCurrency
from procurify_python_sdk.type.simple_user import SimpleUser
from procurify_python_sdk.type.simple_vendor import SimpleVendor

class RequiredPurchaseOrderReadDocs(TypedDict):
    id: int

    number: str

    pref_vendor: SimpleVendor

    promise_date: datetime

    purchased_currency: SimpleCurrency

    purchaser: SimpleUser

    subtotal: str

    total: str

    uuid: str

    total_amount: str

class OptionalPurchaseOrderReadDocs(TypedDict, total=False):
    version: int

    PO_Num: typing.Optional[str]

    date: datetime

    discount: PriceModifierDocs

    freight: typing.Optional[str]

    fulfilment_status: FulfilmentStatusEnum

    item_count: int

    last_modified: datetime

    other: typing.Optional[str]

    procurify_PO: int

    punchout_system: typing.Optional[int]

    purchase_agreement: typing.Optional[int]

    purchase_agreement_status: typing.Optional[ExpenseTypeEnumNullable]

    purchased_currency_rate: typing.Optional[str]

    state: typing.Union[PurchaseOrderStateEnum, NullEnum]

    punchout_items_rejected: bool

    currency: str

    email_status: typing.Optional[str]

    email_status_updated_at: typing.Optional[datetime]

    punchout_supplier_name: typing.Optional[str]

    punchout_supplier_icon: typing.Optional[str]

    punchout_vendor_reference: typing.Optional[int]

    has_blanket_order_items: bool

    expiry_date: typing.Optional[datetime]

class PurchaseOrderReadDocs(RequiredPurchaseOrderReadDocs, OptionalPurchaseOrderReadDocs):
    pass
