# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from procurify_python_sdk.type.address_summary import AddressSummary
from procurify_python_sdk.type.currency_summary import CurrencySummary
from procurify_python_sdk.type.expense_type_enum_nullable import ExpenseTypeEnumNullable
from procurify_python_sdk.type.fulfilment_status_enum import FulfilmentStatusEnum
from procurify_python_sdk.type.null_enum import NullEnum
from procurify_python_sdk.type.price_modifier_docs import PriceModifierDocs
from procurify_python_sdk.type.purchase_order_contract import PurchaseOrderContract
from procurify_python_sdk.type.purchase_order_state_enum import PurchaseOrderStateEnum
from procurify_python_sdk.type.user_summary import UserSummary
from procurify_python_sdk.type.vendor_read import VendorRead

class RequiredPurchaseOrderDocs(TypedDict):
    uuid: str

    purchaser: UserSummary

    buyer_name: str

    buyer_contact: str

    buyer_addressLineOne: str

    buyer_postalCode: str

    buyer_city: str

    buyer_country: str

    buyer_address: AddressSummary

    receiver_name: str

    receiver_contact: str

    receiver_addressLineOne: str

    receiver_postalCode: str

    receiver_city: str

    receiver_country: str

    receiver_address: AddressSummary

    pref_vendor: VendorRead

    payment_terms: str

    shipping_terms: str

    shipping_method: str

    promise_date: datetime

    subtotal: str

    total: str

    purchased_currency: CurrencySummary

    contract: PurchaseOrderContract

class OptionalPurchaseOrderDocs(TypedDict, total=False):
    version: int

    number: str

    procurify_PO: int

    PO_Num: typing.Optional[str]

    date: datetime

    buyer_state_province: str

    receiver_state_province: str

    vendor_name: typing.Optional[str]

    vendor_contact: typing.Optional[str]

    vendor_addressLineOne: typing.Optional[str]

    vendor_postalCode: typing.Optional[str]

    vendor_city: typing.Optional[str]

    vendor_state_province: typing.Optional[str]

    vendor_country: typing.Optional[str]

    freight: typing.Optional[str]

    tax: PriceModifierDocs

    discount: PriceModifierDocs

    other: typing.Optional[str]

    comment: typing.Optional[str]

    purchased_currency_rate: typing.Optional[str]

    active: bool

    state: typing.Union[PurchaseOrderStateEnum, NullEnum]

    fulfilment_status: FulfilmentStatusEnum

    disclaimer_description: typing.Optional[str]

    disclaimer_text: typing.Optional[str]

    recorded_date: typing.Optional[datetime]

    closed_date: typing.Optional[datetime]

    last_modified: datetime

    staged_for_export: bool

    item_count: int

    most_recent_version: int

    punchout_system: typing.Optional[int]

    purchase_agreement: typing.Optional[int]

    purchase_agreement_status: typing.Optional[ExpenseTypeEnumNullable]

    punchout_vendor_reference: typing.Optional[int]

    punchout_supplier_icon: typing.Optional[str]

    punchout_supplier_name: typing.Optional[str]

    has_blanket_order_items: bool

    expiry_date: typing.Optional[datetime]

class PurchaseOrderDocs(RequiredPurchaseOrderDocs, OptionalPurchaseOrderDocs):
    pass
