# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from procurify_python_sdk.type.order_item_purchase_edit_request import OrderItemPurchaseEditRequest
from procurify_python_sdk.type.purchase_order_update_request_custom_fields import PurchaseOrderUpdateRequestCustomFields
from procurify_python_sdk.type.purchase_order_update_request_discount import PurchaseOrderUpdateRequestDiscount
from procurify_python_sdk.type.purchase_order_update_request_tax import PurchaseOrderUpdateRequestTax

class RequiredPurchaseOrderUpdateRequest(TypedDict):
    version: int

    order_items: typing.List[OrderItemPurchaseEditRequest]

    buyer_name: str

    buyer_contact: str

    buyer_addressLineOne: str

    buyer_postalCode: str

    buyer_city: str

    buyer_country: str

    buyer_address: int

    receiver_name: str

    receiver_contact: str

    receiver_addressLineOne: str

    receiver_postalCode: str

    receiver_city: str

    receiver_country: str

    receiver_address: int

    promise_date: datetime

    discount: PurchaseOrderUpdateRequestDiscount

    tax: PurchaseOrderUpdateRequestTax

class OptionalPurchaseOrderUpdateRequest(TypedDict, total=False):
    custom_fields: PurchaseOrderUpdateRequestCustomFields

    PO_Num: typing.Optional[str]

    buyer_state_province: str

    comment: typing.Optional[str]

    receiver_state_province: str

    freight: typing.Optional[str]

    other: typing.Optional[str]

    disclaimer_description: typing.Optional[str]

    disclaimer_text: typing.Optional[str]

    payment_term_ref: typing.Optional[int]

    shipping_term_ref: typing.Optional[int]

    payment_method_ref: typing.Optional[int]

    shipping_method_ref: typing.Optional[int]

    creditcard: typing.Optional[int]

    expiry_date: typing.Optional[datetime]

    contract: typing.Optional[int]

class PurchaseOrderUpdateRequest(RequiredPurchaseOrderUpdateRequest, OptionalPurchaseOrderUpdateRequest):
    pass
