# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from procurify_python_sdk import schemas  # noqa: F401


class Branch(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "name",
            "phoneOne",
            "localCurrency",
        }
        
        class properties:
            
            
            class name(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 150
            
            
            class phoneOne(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 20
            localCurrency = schemas.IntSchema
            id = schemas.IntSchema
            
            
            class external_id(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 100
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'external_id':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class url(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'uri'
                    max_length = 200
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'url':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            logo = schemas.StrSchema
        
            @staticmethod
            def language() -> typing.Type['LanguageEnum']:
                return LanguageEnum
            multipleLocations = schemas.BoolSchema
            
            
            class locationTimezone(
                schemas.ComposedBase,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    
                    @classmethod
                    @functools.lru_cache()
                    def one_of(cls):
                        # we need this here to make our import statements work
                        # we must store _composed_schemas in here so the code is only run
                        # when we invoke this method. If we kept this at the class
                        # level we would get an error because the class level
                        # code would be run when this module is imported, and these composed
                        # classes don't exist yet because their module has not finished
                        # loading
                        return [
                            LocationTimezoneEnum,
                            BlankEnum,
                            NullEnum,
                        ]
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'locationTimezone':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class userLimit(
                schemas.Int64Schema
            ):
            
            
                class MetaOapg:
                    format = 'int64'
                    inclusive_maximum = 4294967295
                    inclusive_minimum = 0
            budgetOvertureToggle = schemas.BoolSchema
            purchase_filtering = schemas.BoolSchema
            catalog_permission = schemas.BoolSchema
            separate_expense_approval = schemas.BoolSchema
            standalone_travel_approval = schemas.BoolSchema
            
            
            class phoneTwo(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 20
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'phoneTwo':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class fax(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 20
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'fax':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class email(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'email'
                    max_length = 254
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'email':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class fiscalYearEndDay(
                schemas.Int64Base,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'int64'
                    inclusive_maximum = 4294967295
                    inclusive_minimum = 0
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'fiscalYearEndDay':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class fiscalYearEndMonth(
                schemas.Int64Base,
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    format = 'int64'
                    inclusive_maximum = 4294967295
                    inclusive_minimum = 0
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'fiscalYearEndMonth':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            beginDate = schemas.DateTimeSchema
            ported = schemas.BoolSchema
            
            
            class port_date(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'port_date':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            active = schemas.BoolSchema
            activated = schemas.BoolSchema
        
            @staticmethod
            def setup_stage() -> typing.Type['SetupStageEnum']:
                return SetupStageEnum
            
            
            class contactPerson(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'contactPerson':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class buyerAddress(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'buyerAddress':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class shippingAddress(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'shippingAddress':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "name": name,
                "phoneOne": phoneOne,
                "localCurrency": localCurrency,
                "id": id,
                "external_id": external_id,
                "url": url,
                "logo": logo,
                "language": language,
                "multipleLocations": multipleLocations,
                "locationTimezone": locationTimezone,
                "userLimit": userLimit,
                "budgetOvertureToggle": budgetOvertureToggle,
                "purchase_filtering": purchase_filtering,
                "catalog_permission": catalog_permission,
                "separate_expense_approval": separate_expense_approval,
                "standalone_travel_approval": standalone_travel_approval,
                "phoneTwo": phoneTwo,
                "fax": fax,
                "email": email,
                "fiscalYearEndDay": fiscalYearEndDay,
                "fiscalYearEndMonth": fiscalYearEndMonth,
                "beginDate": beginDate,
                "ported": ported,
                "port_date": port_date,
                "active": active,
                "activated": activated,
                "setup_stage": setup_stage,
                "contactPerson": contactPerson,
                "buyerAddress": buyerAddress,
                "shippingAddress": shippingAddress,
            }
    
    name: MetaOapg.properties.name
    phoneOne: MetaOapg.properties.phoneOne
    localCurrency: MetaOapg.properties.localCurrency
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phoneOne"]) -> MetaOapg.properties.phoneOne: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["localCurrency"]) -> MetaOapg.properties.localCurrency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["external_id"]) -> MetaOapg.properties.external_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["url"]) -> MetaOapg.properties.url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["logo"]) -> MetaOapg.properties.logo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["language"]) -> 'LanguageEnum': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["multipleLocations"]) -> MetaOapg.properties.multipleLocations: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locationTimezone"]) -> MetaOapg.properties.locationTimezone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["userLimit"]) -> MetaOapg.properties.userLimit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["budgetOvertureToggle"]) -> MetaOapg.properties.budgetOvertureToggle: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["purchase_filtering"]) -> MetaOapg.properties.purchase_filtering: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["catalog_permission"]) -> MetaOapg.properties.catalog_permission: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["separate_expense_approval"]) -> MetaOapg.properties.separate_expense_approval: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["standalone_travel_approval"]) -> MetaOapg.properties.standalone_travel_approval: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phoneTwo"]) -> MetaOapg.properties.phoneTwo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fax"]) -> MetaOapg.properties.fax: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fiscalYearEndDay"]) -> MetaOapg.properties.fiscalYearEndDay: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fiscalYearEndMonth"]) -> MetaOapg.properties.fiscalYearEndMonth: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["beginDate"]) -> MetaOapg.properties.beginDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ported"]) -> MetaOapg.properties.ported: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["port_date"]) -> MetaOapg.properties.port_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["active"]) -> MetaOapg.properties.active: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["activated"]) -> MetaOapg.properties.activated: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["setup_stage"]) -> 'SetupStageEnum': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contactPerson"]) -> MetaOapg.properties.contactPerson: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["buyerAddress"]) -> MetaOapg.properties.buyerAddress: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shippingAddress"]) -> MetaOapg.properties.shippingAddress: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "phoneOne", "localCurrency", "id", "external_id", "url", "logo", "language", "multipleLocations", "locationTimezone", "userLimit", "budgetOvertureToggle", "purchase_filtering", "catalog_permission", "separate_expense_approval", "standalone_travel_approval", "phoneTwo", "fax", "email", "fiscalYearEndDay", "fiscalYearEndMonth", "beginDate", "ported", "port_date", "active", "activated", "setup_stage", "contactPerson", "buyerAddress", "shippingAddress", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phoneOne"]) -> MetaOapg.properties.phoneOne: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["localCurrency"]) -> MetaOapg.properties.localCurrency: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["external_id"]) -> typing.Union[MetaOapg.properties.external_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["url"]) -> typing.Union[MetaOapg.properties.url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["logo"]) -> typing.Union[MetaOapg.properties.logo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["language"]) -> typing.Union['LanguageEnum', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["multipleLocations"]) -> typing.Union[MetaOapg.properties.multipleLocations, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locationTimezone"]) -> typing.Union[MetaOapg.properties.locationTimezone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["userLimit"]) -> typing.Union[MetaOapg.properties.userLimit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["budgetOvertureToggle"]) -> typing.Union[MetaOapg.properties.budgetOvertureToggle, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["purchase_filtering"]) -> typing.Union[MetaOapg.properties.purchase_filtering, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["catalog_permission"]) -> typing.Union[MetaOapg.properties.catalog_permission, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["separate_expense_approval"]) -> typing.Union[MetaOapg.properties.separate_expense_approval, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["standalone_travel_approval"]) -> typing.Union[MetaOapg.properties.standalone_travel_approval, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phoneTwo"]) -> typing.Union[MetaOapg.properties.phoneTwo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fax"]) -> typing.Union[MetaOapg.properties.fax, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> typing.Union[MetaOapg.properties.email, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fiscalYearEndDay"]) -> typing.Union[MetaOapg.properties.fiscalYearEndDay, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fiscalYearEndMonth"]) -> typing.Union[MetaOapg.properties.fiscalYearEndMonth, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["beginDate"]) -> typing.Union[MetaOapg.properties.beginDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ported"]) -> typing.Union[MetaOapg.properties.ported, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["port_date"]) -> typing.Union[MetaOapg.properties.port_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["active"]) -> typing.Union[MetaOapg.properties.active, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["activated"]) -> typing.Union[MetaOapg.properties.activated, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["setup_stage"]) -> typing.Union['SetupStageEnum', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contactPerson"]) -> typing.Union[MetaOapg.properties.contactPerson, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["buyerAddress"]) -> typing.Union[MetaOapg.properties.buyerAddress, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shippingAddress"]) -> typing.Union[MetaOapg.properties.shippingAddress, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "phoneOne", "localCurrency", "id", "external_id", "url", "logo", "language", "multipleLocations", "locationTimezone", "userLimit", "budgetOvertureToggle", "purchase_filtering", "catalog_permission", "separate_expense_approval", "standalone_travel_approval", "phoneTwo", "fax", "email", "fiscalYearEndDay", "fiscalYearEndMonth", "beginDate", "ported", "port_date", "active", "activated", "setup_stage", "contactPerson", "buyerAddress", "shippingAddress", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        phoneOne: typing.Union[MetaOapg.properties.phoneOne, str, ],
        localCurrency: typing.Union[MetaOapg.properties.localCurrency, decimal.Decimal, int, ],
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        external_id: typing.Union[MetaOapg.properties.external_id, None, str, schemas.Unset] = schemas.unset,
        url: typing.Union[MetaOapg.properties.url, None, str, schemas.Unset] = schemas.unset,
        logo: typing.Union[MetaOapg.properties.logo, str, schemas.Unset] = schemas.unset,
        language: typing.Union['LanguageEnum', schemas.Unset] = schemas.unset,
        multipleLocations: typing.Union[MetaOapg.properties.multipleLocations, bool, schemas.Unset] = schemas.unset,
        locationTimezone: typing.Union[MetaOapg.properties.locationTimezone, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        userLimit: typing.Union[MetaOapg.properties.userLimit, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        budgetOvertureToggle: typing.Union[MetaOapg.properties.budgetOvertureToggle, bool, schemas.Unset] = schemas.unset,
        purchase_filtering: typing.Union[MetaOapg.properties.purchase_filtering, bool, schemas.Unset] = schemas.unset,
        catalog_permission: typing.Union[MetaOapg.properties.catalog_permission, bool, schemas.Unset] = schemas.unset,
        separate_expense_approval: typing.Union[MetaOapg.properties.separate_expense_approval, bool, schemas.Unset] = schemas.unset,
        standalone_travel_approval: typing.Union[MetaOapg.properties.standalone_travel_approval, bool, schemas.Unset] = schemas.unset,
        phoneTwo: typing.Union[MetaOapg.properties.phoneTwo, None, str, schemas.Unset] = schemas.unset,
        fax: typing.Union[MetaOapg.properties.fax, None, str, schemas.Unset] = schemas.unset,
        email: typing.Union[MetaOapg.properties.email, None, str, schemas.Unset] = schemas.unset,
        fiscalYearEndDay: typing.Union[MetaOapg.properties.fiscalYearEndDay, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        fiscalYearEndMonth: typing.Union[MetaOapg.properties.fiscalYearEndMonth, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        beginDate: typing.Union[MetaOapg.properties.beginDate, str, datetime, schemas.Unset] = schemas.unset,
        ported: typing.Union[MetaOapg.properties.ported, bool, schemas.Unset] = schemas.unset,
        port_date: typing.Union[MetaOapg.properties.port_date, None, str, datetime, schemas.Unset] = schemas.unset,
        active: typing.Union[MetaOapg.properties.active, bool, schemas.Unset] = schemas.unset,
        activated: typing.Union[MetaOapg.properties.activated, bool, schemas.Unset] = schemas.unset,
        setup_stage: typing.Union['SetupStageEnum', schemas.Unset] = schemas.unset,
        contactPerson: typing.Union[MetaOapg.properties.contactPerson, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        buyerAddress: typing.Union[MetaOapg.properties.buyerAddress, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        shippingAddress: typing.Union[MetaOapg.properties.shippingAddress, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Branch':
        return super().__new__(
            cls,
            *args,
            name=name,
            phoneOne=phoneOne,
            localCurrency=localCurrency,
            id=id,
            external_id=external_id,
            url=url,
            logo=logo,
            language=language,
            multipleLocations=multipleLocations,
            locationTimezone=locationTimezone,
            userLimit=userLimit,
            budgetOvertureToggle=budgetOvertureToggle,
            purchase_filtering=purchase_filtering,
            catalog_permission=catalog_permission,
            separate_expense_approval=separate_expense_approval,
            standalone_travel_approval=standalone_travel_approval,
            phoneTwo=phoneTwo,
            fax=fax,
            email=email,
            fiscalYearEndDay=fiscalYearEndDay,
            fiscalYearEndMonth=fiscalYearEndMonth,
            beginDate=beginDate,
            ported=ported,
            port_date=port_date,
            active=active,
            activated=activated,
            setup_stage=setup_stage,
            contactPerson=contactPerson,
            buyerAddress=buyerAddress,
            shippingAddress=shippingAddress,
            _configuration=_configuration,
            **kwargs,
        )

from procurify_python_sdk.model.blank_enum import BlankEnum
from procurify_python_sdk.model.language_enum import LanguageEnum
from procurify_python_sdk.model.location_timezone_enum import LocationTimezoneEnum
from procurify_python_sdk.model.null_enum import NullEnum
from procurify_python_sdk.model.setup_stage_enum import SetupStageEnum
