# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from procurify_python_sdk import schemas  # noqa: F401


class CreditCardRead(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "vendor",
            "assignees",
            "currency",
        }
        
        class properties:
        
            @staticmethod
            def vendor() -> typing.Type['SimpleVendor']:
                return SimpleVendor
        
            @staticmethod
            def currency() -> typing.Type['Currency']:
                return Currency
            
            
            class assignees(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['SimpleUserSummary']:
                        return SimpleUserSummary
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['SimpleUserSummary'], typing.List['SimpleUserSummary']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'assignees':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'SimpleUserSummary':
                    return super().__getitem__(i)
            id = schemas.IntSchema
            
            
            class name(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 255
            
            
            class number(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 19
                    regex=[{
                        'pattern': r'^[0-9]{4}$',
                    }]
        
            @staticmethod
            def type() -> typing.Type['CreditCardTypeEnum']:
                return CreditCardTypeEnum
            
            
            class balance(
                schemas.IntBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneDecimalMixin
            ):
            
            
                class MetaOapg:
                    inclusive_maximum = 2147483647
                    inclusive_minimum = -2147483648
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, decimal.Decimal, int, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'balance':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            last_reconciliation_date = schemas.DateTimeSchema
            last_reconciliation_balance = schemas.Float64Schema
        
            @staticmethod
            def session() -> typing.Type['SessionCreate']:
                return SessionCreate
            
            
            class gl_code(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 100
            last_statement_date = schemas.DateTimeSchema
            __annotations__ = {
                "vendor": vendor,
                "currency": currency,
                "assignees": assignees,
                "id": id,
                "name": name,
                "number": number,
                "type": type,
                "balance": balance,
                "last_reconciliation_date": last_reconciliation_date,
                "last_reconciliation_balance": last_reconciliation_balance,
                "session": session,
                "gl_code": gl_code,
                "last_statement_date": last_statement_date,
            }
    
    vendor: 'SimpleVendor'
    assignees: MetaOapg.properties.assignees
    currency: 'Currency'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vendor"]) -> 'SimpleVendor': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency"]) -> 'Currency': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assignees"]) -> MetaOapg.properties.assignees: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["number"]) -> MetaOapg.properties.number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> 'CreditCardTypeEnum': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["balance"]) -> MetaOapg.properties.balance: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["last_reconciliation_date"]) -> MetaOapg.properties.last_reconciliation_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["last_reconciliation_balance"]) -> MetaOapg.properties.last_reconciliation_balance: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["session"]) -> 'SessionCreate': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gl_code"]) -> MetaOapg.properties.gl_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["last_statement_date"]) -> MetaOapg.properties.last_statement_date: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["vendor", "currency", "assignees", "id", "name", "number", "type", "balance", "last_reconciliation_date", "last_reconciliation_balance", "session", "gl_code", "last_statement_date", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vendor"]) -> 'SimpleVendor': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency"]) -> 'Currency': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assignees"]) -> MetaOapg.properties.assignees: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["number"]) -> typing.Union[MetaOapg.properties.number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union['CreditCardTypeEnum', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["balance"]) -> typing.Union[MetaOapg.properties.balance, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["last_reconciliation_date"]) -> typing.Union[MetaOapg.properties.last_reconciliation_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["last_reconciliation_balance"]) -> typing.Union[MetaOapg.properties.last_reconciliation_balance, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["session"]) -> typing.Union['SessionCreate', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gl_code"]) -> typing.Union[MetaOapg.properties.gl_code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["last_statement_date"]) -> typing.Union[MetaOapg.properties.last_statement_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["vendor", "currency", "assignees", "id", "name", "number", "type", "balance", "last_reconciliation_date", "last_reconciliation_balance", "session", "gl_code", "last_statement_date", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        vendor: 'SimpleVendor',
        assignees: typing.Union[MetaOapg.properties.assignees, list, tuple, ],
        currency: 'Currency',
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        number: typing.Union[MetaOapg.properties.number, str, schemas.Unset] = schemas.unset,
        type: typing.Union['CreditCardTypeEnum', schemas.Unset] = schemas.unset,
        balance: typing.Union[MetaOapg.properties.balance, None, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        last_reconciliation_date: typing.Union[MetaOapg.properties.last_reconciliation_date, str, datetime, schemas.Unset] = schemas.unset,
        last_reconciliation_balance: typing.Union[MetaOapg.properties.last_reconciliation_balance, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        session: typing.Union['SessionCreate', schemas.Unset] = schemas.unset,
        gl_code: typing.Union[MetaOapg.properties.gl_code, str, schemas.Unset] = schemas.unset,
        last_statement_date: typing.Union[MetaOapg.properties.last_statement_date, str, datetime, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CreditCardRead':
        return super().__new__(
            cls,
            *args,
            vendor=vendor,
            assignees=assignees,
            currency=currency,
            id=id,
            name=name,
            number=number,
            type=type,
            balance=balance,
            last_reconciliation_date=last_reconciliation_date,
            last_reconciliation_balance=last_reconciliation_balance,
            session=session,
            gl_code=gl_code,
            last_statement_date=last_statement_date,
            _configuration=_configuration,
            **kwargs,
        )

from procurify_python_sdk.model.credit_card_type_enum import CreditCardTypeEnum
from procurify_python_sdk.model.currency import Currency
from procurify_python_sdk.model.session_create import SessionCreate
from procurify_python_sdk.model.simple_user_summary import SimpleUserSummary
from procurify_python_sdk.model.simple_vendor import SimpleVendor
