# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from procurify_python_sdk import schemas  # noqa: F401


class LocationTimezoneEnum(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        enum_value_to_name = {
            "Africa/Abidjan": "AFRICA_ABIDJAN",
            "Africa/Accra": "AFRICA_ACCRA",
            "Africa/Addis_Ababa": "AFRICA_ADDIS_ABABA",
            "Africa/Algiers": "AFRICA_ALGIERS",
            "Africa/Asmara": "AFRICA_ASMARA",
            "Africa/Bamako": "AFRICA_BAMAKO",
            "Africa/Bangui": "AFRICA_BANGUI",
            "Africa/Banjul": "AFRICA_BANJUL",
            "Africa/Bissau": "AFRICA_BISSAU",
            "Africa/Blantyre": "AFRICA_BLANTYRE",
            "Africa/Brazzaville": "AFRICA_BRAZZAVILLE",
            "Africa/Bujumbura": "AFRICA_BUJUMBURA",
            "Africa/Cairo": "AFRICA_CAIRO",
            "Africa/Casablanca": "AFRICA_CASABLANCA",
            "Africa/Ceuta": "AFRICA_CEUTA",
            "Africa/Conakry": "AFRICA_CONAKRY",
            "Africa/Dakar": "AFRICA_DAKAR",
            "Africa/Dar_es_Salaam": "AFRICA_DAR_ES_SALAAM",
            "Africa/Djibouti": "AFRICA_DJIBOUTI",
            "Africa/Douala": "AFRICA_DOUALA",
            "Africa/El_Aaiun": "AFRICA_EL_AAIUN",
            "Africa/Freetown": "AFRICA_FREETOWN",
            "Africa/Gaborone": "AFRICA_GABORONE",
            "Africa/Harare": "AFRICA_HARARE",
            "Africa/Johannesburg": "AFRICA_JOHANNESBURG",
            "Africa/Juba": "AFRICA_JUBA",
            "Africa/Kampala": "AFRICA_KAMPALA",
            "Africa/Khartoum": "AFRICA_KHARTOUM",
            "Africa/Kigali": "AFRICA_KIGALI",
            "Africa/Kinshasa": "AFRICA_KINSHASA",
            "Africa/Lagos": "AFRICA_LAGOS",
            "Africa/Libreville": "AFRICA_LIBREVILLE",
            "Africa/Lome": "AFRICA_LOME",
            "Africa/Luanda": "AFRICA_LUANDA",
            "Africa/Lubumbashi": "AFRICA_LUBUMBASHI",
            "Africa/Lusaka": "AFRICA_LUSAKA",
            "Africa/Malabo": "AFRICA_MALABO",
            "Africa/Maputo": "AFRICA_MAPUTO",
            "Africa/Maseru": "AFRICA_MASERU",
            "Africa/Mbabane": "AFRICA_MBABANE",
            "Africa/Mogadishu": "AFRICA_MOGADISHU",
            "Africa/Monrovia": "AFRICA_MONROVIA",
            "Africa/Nairobi": "AFRICA_NAIROBI",
            "Africa/Ndjamena": "AFRICA_NDJAMENA",
            "Africa/Niamey": "AFRICA_NIAMEY",
            "Africa/Nouakchott": "AFRICA_NOUAKCHOTT",
            "Africa/Ouagadougou": "AFRICA_OUAGADOUGOU",
            "Africa/Porto-Novo": "AFRICA_PORTONOVO",
            "Africa/Sao_Tome": "AFRICA_SAO_TOME",
            "Africa/Tripoli": "AFRICA_TRIPOLI",
            "Africa/Tunis": "AFRICA_TUNIS",
            "Africa/Windhoek": "AFRICA_WINDHOEK",
            "America/Adak": "AMERICA_ADAK",
            "America/Anchorage": "AMERICA_ANCHORAGE",
            "America/Anguilla": "AMERICA_ANGUILLA",
            "America/Antigua": "AMERICA_ANTIGUA",
            "America/Araguaina": "AMERICA_ARAGUAINA",
            "America/Argentina/Buenos_Aires": "AMERICA_ARGENTINA_BUENOS_AIRES",
            "America/Argentina/Catamarca": "AMERICA_ARGENTINA_CATAMARCA",
            "America/Argentina/Cordoba": "AMERICA_ARGENTINA_CORDOBA",
            "America/Argentina/Jujuy": "AMERICA_ARGENTINA_JUJUY",
            "America/Argentina/La_Rioja": "AMERICA_ARGENTINA_LA_RIOJA",
            "America/Argentina/Mendoza": "AMERICA_ARGENTINA_MENDOZA",
            "America/Argentina/Rio_Gallegos": "AMERICA_ARGENTINA_RIO_GALLEGOS",
            "America/Argentina/Salta": "AMERICA_ARGENTINA_SALTA",
            "America/Argentina/San_Juan": "AMERICA_ARGENTINA_SAN_JUAN",
            "America/Argentina/San_Luis": "AMERICA_ARGENTINA_SAN_LUIS",
            "America/Argentina/Tucuman": "AMERICA_ARGENTINA_TUCUMAN",
            "America/Argentina/Ushuaia": "AMERICA_ARGENTINA_USHUAIA",
            "America/Aruba": "AMERICA_ARUBA",
            "America/Asuncion": "AMERICA_ASUNCION",
            "America/Atikokan": "AMERICA_ATIKOKAN",
            "America/Bahia": "AMERICA_BAHIA",
            "America/Bahia_Banderas": "AMERICA_BAHIA_BANDERAS",
            "America/Barbados": "AMERICA_BARBADOS",
            "America/Belem": "AMERICA_BELEM",
            "America/Belize": "AMERICA_BELIZE",
            "America/Blanc-Sablon": "AMERICA_BLANCSABLON",
            "America/Boa_Vista": "AMERICA_BOA_VISTA",
            "America/Bogota": "AMERICA_BOGOTA",
            "America/Boise": "AMERICA_BOISE",
            "America/Cambridge_Bay": "AMERICA_CAMBRIDGE_BAY",
            "America/Campo_Grande": "AMERICA_CAMPO_GRANDE",
            "America/Cancun": "AMERICA_CANCUN",
            "America/Caracas": "AMERICA_CARACAS",
            "America/Cayenne": "AMERICA_CAYENNE",
            "America/Cayman": "AMERICA_CAYMAN",
            "America/Chicago": "AMERICA_CHICAGO",
            "America/Chihuahua": "AMERICA_CHIHUAHUA",
            "America/Costa_Rica": "AMERICA_COSTA_RICA",
            "America/Creston": "AMERICA_CRESTON",
            "America/Cuiaba": "AMERICA_CUIABA",
            "America/Curacao": "AMERICA_CURACAO",
            "America/Danmarkshavn": "AMERICA_DANMARKSHAVN",
            "America/Dawson": "AMERICA_DAWSON",
            "America/Dawson_Creek": "AMERICA_DAWSON_CREEK",
            "America/Denver": "AMERICA_DENVER",
            "America/Detroit": "AMERICA_DETROIT",
            "America/Dominica": "AMERICA_DOMINICA",
            "America/Edmonton": "AMERICA_EDMONTON",
            "America/Eirunepe": "AMERICA_EIRUNEPE",
            "America/El_Salvador": "AMERICA_EL_SALVADOR",
            "America/Fort_Nelson": "AMERICA_FORT_NELSON",
            "America/Fortaleza": "AMERICA_FORTALEZA",
            "America/Glace_Bay": "AMERICA_GLACE_BAY",
            "America/Godthab": "AMERICA_GODTHAB",
            "America/Goose_Bay": "AMERICA_GOOSE_BAY",
            "America/Grand_Turk": "AMERICA_GRAND_TURK",
            "America/Grenada": "AMERICA_GRENADA",
            "America/Guadeloupe": "AMERICA_GUADELOUPE",
            "America/Guatemala": "AMERICA_GUATEMALA",
            "America/Guayaquil": "AMERICA_GUAYAQUIL",
            "America/Guyana": "AMERICA_GUYANA",
            "America/Halifax": "AMERICA_HALIFAX",
            "America/Havana": "AMERICA_HAVANA",
            "America/Hermosillo": "AMERICA_HERMOSILLO",
            "America/Indiana/Indianapolis": "AMERICA_INDIANA_INDIANAPOLIS",
            "America/Indiana/Knox": "AMERICA_INDIANA_KNOX",
            "America/Indiana/Marengo": "AMERICA_INDIANA_MARENGO",
            "America/Indiana/Petersburg": "AMERICA_INDIANA_PETERSBURG",
            "America/Indiana/Tell_City": "AMERICA_INDIANA_TELL_CITY",
            "America/Indiana/Vevay": "AMERICA_INDIANA_VEVAY",
            "America/Indiana/Vincennes": "AMERICA_INDIANA_VINCENNES",
            "America/Indiana/Winamac": "AMERICA_INDIANA_WINAMAC",
            "America/Inuvik": "AMERICA_INUVIK",
            "America/Iqaluit": "AMERICA_IQALUIT",
            "America/Jamaica": "AMERICA_JAMAICA",
            "America/Juneau": "AMERICA_JUNEAU",
            "America/Kentucky/Louisville": "AMERICA_KENTUCKY_LOUISVILLE",
            "America/Kentucky/Monticello": "AMERICA_KENTUCKY_MONTICELLO",
            "America/Kralendijk": "AMERICA_KRALENDIJK",
            "America/La_Paz": "AMERICA_LA_PAZ",
            "America/Lima": "AMERICA_LIMA",
            "America/Los_Angeles": "AMERICA_LOS_ANGELES",
            "America/Lower_Princes": "AMERICA_LOWER_PRINCES",
            "America/Maceio": "AMERICA_MACEIO",
            "America/Managua": "AMERICA_MANAGUA",
            "America/Manaus": "AMERICA_MANAUS",
            "America/Marigot": "AMERICA_MARIGOT",
            "America/Martinique": "AMERICA_MARTINIQUE",
            "America/Matamoros": "AMERICA_MATAMOROS",
            "America/Mazatlan": "AMERICA_MAZATLAN",
            "America/Menominee": "AMERICA_MENOMINEE",
            "America/Merida": "AMERICA_MERIDA",
            "America/Metlakatla": "AMERICA_METLAKATLA",
            "America/Mexico_City": "AMERICA_MEXICO_CITY",
            "America/Miquelon": "AMERICA_MIQUELON",
            "America/Moncton": "AMERICA_MONCTON",
            "America/Monterrey": "AMERICA_MONTERREY",
            "America/Montevideo": "AMERICA_MONTEVIDEO",
            "America/Montserrat": "AMERICA_MONTSERRAT",
            "America/Nassau": "AMERICA_NASSAU",
            "America/New_York": "AMERICA_NEW_YORK",
            "America/Nipigon": "AMERICA_NIPIGON",
            "America/Nome": "AMERICA_NOME",
            "America/Noronha": "AMERICA_NORONHA",
            "America/North_Dakota/Beulah": "AMERICA_NORTH_DAKOTA_BEULAH",
            "America/North_Dakota/Center": "AMERICA_NORTH_DAKOTA_CENTER",
            "America/North_Dakota/New_Salem": "AMERICA_NORTH_DAKOTA_NEW_SALEM",
            "America/Ojinaga": "AMERICA_OJINAGA",
            "America/Panama": "AMERICA_PANAMA",
            "America/Pangnirtung": "AMERICA_PANGNIRTUNG",
            "America/Paramaribo": "AMERICA_PARAMARIBO",
            "America/Phoenix": "AMERICA_PHOENIX",
            "America/Port-au-Prince": "AMERICA_PORTAUPRINCE",
            "America/Port_of_Spain": "AMERICA_PORT_OF_SPAIN",
            "America/Porto_Velho": "AMERICA_PORTO_VELHO",
            "America/Puerto_Rico": "AMERICA_PUERTO_RICO",
            "America/Punta_Arenas": "AMERICA_PUNTA_ARENAS",
            "America/Rainy_River": "AMERICA_RAINY_RIVER",
            "America/Rankin_Inlet": "AMERICA_RANKIN_INLET",
            "America/Recife": "AMERICA_RECIFE",
            "America/Regina": "AMERICA_REGINA",
            "America/Resolute": "AMERICA_RESOLUTE",
            "America/Rio_Branco": "AMERICA_RIO_BRANCO",
            "America/Santarem": "AMERICA_SANTAREM",
            "America/Santiago": "AMERICA_SANTIAGO",
            "America/Santo_Domingo": "AMERICA_SANTO_DOMINGO",
            "America/Sao_Paulo": "AMERICA_SAO_PAULO",
            "America/Scoresbysund": "AMERICA_SCORESBYSUND",
            "America/Sitka": "AMERICA_SITKA",
            "America/St_Barthelemy": "AMERICA_ST_BARTHELEMY",
            "America/St_Johns": "AMERICA_ST_JOHNS",
            "America/St_Kitts": "AMERICA_ST_KITTS",
            "America/St_Lucia": "AMERICA_ST_LUCIA",
            "America/St_Thomas": "AMERICA_ST_THOMAS",
            "America/St_Vincent": "AMERICA_ST_VINCENT",
            "America/Swift_Current": "AMERICA_SWIFT_CURRENT",
            "America/Tegucigalpa": "AMERICA_TEGUCIGALPA",
            "America/Thule": "AMERICA_THULE",
            "America/Thunder_Bay": "AMERICA_THUNDER_BAY",
            "America/Tijuana": "AMERICA_TIJUANA",
            "America/Toronto": "AMERICA_TORONTO",
            "America/Tortola": "AMERICA_TORTOLA",
            "America/Vancouver": "AMERICA_VANCOUVER",
            "America/Whitehorse": "AMERICA_WHITEHORSE",
            "America/Winnipeg": "AMERICA_WINNIPEG",
            "America/Yakutat": "AMERICA_YAKUTAT",
            "America/Yellowknife": "AMERICA_YELLOWKNIFE",
            "Antarctica/Casey": "ANTARCTICA_CASEY",
            "Antarctica/Davis": "ANTARCTICA_DAVIS",
            "Antarctica/DumontDUrville": "ANTARCTICA_DUMONT_DURVILLE",
            "Antarctica/Macquarie": "ANTARCTICA_MACQUARIE",
            "Antarctica/Mawson": "ANTARCTICA_MAWSON",
            "Antarctica/McMurdo": "ANTARCTICA_MC_MURDO",
            "Antarctica/Palmer": "ANTARCTICA_PALMER",
            "Antarctica/Rothera": "ANTARCTICA_ROTHERA",
            "Antarctica/Syowa": "ANTARCTICA_SYOWA",
            "Antarctica/Troll": "ANTARCTICA_TROLL",
            "Antarctica/Vostok": "ANTARCTICA_VOSTOK",
            "Arctic/Longyearbyen": "ARCTIC_LONGYEARBYEN",
            "Asia/Aden": "ASIA_ADEN",
            "Asia/Almaty": "ASIA_ALMATY",
            "Asia/Amman": "ASIA_AMMAN",
            "Asia/Anadyr": "ASIA_ANADYR",
            "Asia/Aqtau": "ASIA_AQTAU",
            "Asia/Aqtobe": "ASIA_AQTOBE",
            "Asia/Ashgabat": "ASIA_ASHGABAT",
            "Asia/Atyrau": "ASIA_ATYRAU",
            "Asia/Baghdad": "ASIA_BAGHDAD",
            "Asia/Bahrain": "ASIA_BAHRAIN",
            "Asia/Baku": "ASIA_BAKU",
            "Asia/Bangkok": "ASIA_BANGKOK",
            "Asia/Barnaul": "ASIA_BARNAUL",
            "Asia/Beirut": "ASIA_BEIRUT",
            "Asia/Bishkek": "ASIA_BISHKEK",
            "Asia/Brunei": "ASIA_BRUNEI",
            "Asia/Chita": "ASIA_CHITA",
            "Asia/Choibalsan": "ASIA_CHOIBALSAN",
            "Asia/Colombo": "ASIA_COLOMBO",
            "Asia/Damascus": "ASIA_DAMASCUS",
            "Asia/Dhaka": "ASIA_DHAKA",
            "Asia/Dili": "ASIA_DILI",
            "Asia/Dubai": "ASIA_DUBAI",
            "Asia/Dushanbe": "ASIA_DUSHANBE",
            "Asia/Famagusta": "ASIA_FAMAGUSTA",
            "Asia/Gaza": "ASIA_GAZA",
            "Asia/Hebron": "ASIA_HEBRON",
            "Asia/Ho_Chi_Minh": "ASIA_HO_CHI_MINH",
            "Asia/Hong_Kong": "ASIA_HONG_KONG",
            "Asia/Hovd": "ASIA_HOVD",
            "Asia/Irkutsk": "ASIA_IRKUTSK",
            "Asia/Jakarta": "ASIA_JAKARTA",
            "Asia/Jayapura": "ASIA_JAYAPURA",
            "Asia/Jerusalem": "ASIA_JERUSALEM",
            "Asia/Kabul": "ASIA_KABUL",
            "Asia/Kamchatka": "ASIA_KAMCHATKA",
            "Asia/Karachi": "ASIA_KARACHI",
            "Asia/Kathmandu": "ASIA_KATHMANDU",
            "Asia/Khandyga": "ASIA_KHANDYGA",
            "Asia/Kolkata": "ASIA_KOLKATA",
            "Asia/Krasnoyarsk": "ASIA_KRASNOYARSK",
            "Asia/Kuala_Lumpur": "ASIA_KUALA_LUMPUR",
            "Asia/Kuching": "ASIA_KUCHING",
            "Asia/Kuwait": "ASIA_KUWAIT",
            "Asia/Macau": "ASIA_MACAU",
            "Asia/Magadan": "ASIA_MAGADAN",
            "Asia/Makassar": "ASIA_MAKASSAR",
            "Asia/Manila": "ASIA_MANILA",
            "Asia/Muscat": "ASIA_MUSCAT",
            "Asia/Nicosia": "ASIA_NICOSIA",
            "Asia/Novokuznetsk": "ASIA_NOVOKUZNETSK",
            "Asia/Novosibirsk": "ASIA_NOVOSIBIRSK",
            "Asia/Omsk": "ASIA_OMSK",
            "Asia/Oral": "ASIA_ORAL",
            "Asia/Phnom_Penh": "ASIA_PHNOM_PENH",
            "Asia/Pontianak": "ASIA_PONTIANAK",
            "Asia/Pyongyang": "ASIA_PYONGYANG",
            "Asia/Qatar": "ASIA_QATAR",
            "Asia/Qyzylorda": "ASIA_QYZYLORDA",
            "Asia/Riyadh": "ASIA_RIYADH",
            "Asia/Sakhalin": "ASIA_SAKHALIN",
            "Asia/Samarkand": "ASIA_SAMARKAND",
            "Asia/Seoul": "ASIA_SEOUL",
            "Asia/Shanghai": "ASIA_SHANGHAI",
            "Asia/Singapore": "ASIA_SINGAPORE",
            "Asia/Srednekolymsk": "ASIA_SREDNEKOLYMSK",
            "Asia/Taipei": "ASIA_TAIPEI",
            "Asia/Tashkent": "ASIA_TASHKENT",
            "Asia/Tbilisi": "ASIA_TBILISI",
            "Asia/Tehran": "ASIA_TEHRAN",
            "Asia/Thimphu": "ASIA_THIMPHU",
            "Asia/Tokyo": "ASIA_TOKYO",
            "Asia/Tomsk": "ASIA_TOMSK",
            "Asia/Ulaanbaatar": "ASIA_ULAANBAATAR",
            "Asia/Urumqi": "ASIA_URUMQI",
            "Asia/Ust-Nera": "ASIA_USTNERA",
            "Asia/Vientiane": "ASIA_VIENTIANE",
            "Asia/Vladivostok": "ASIA_VLADIVOSTOK",
            "Asia/Yakutsk": "ASIA_YAKUTSK",
            "Asia/Yangon": "ASIA_YANGON",
            "Asia/Yekaterinburg": "ASIA_YEKATERINBURG",
            "Asia/Yerevan": "ASIA_YEREVAN",
            "Atlantic/Azores": "ATLANTIC_AZORES",
            "Atlantic/Bermuda": "ATLANTIC_BERMUDA",
            "Atlantic/Canary": "ATLANTIC_CANARY",
            "Atlantic/Cape_Verde": "ATLANTIC_CAPE_VERDE",
            "Atlantic/Faroe": "ATLANTIC_FAROE",
            "Atlantic/Madeira": "ATLANTIC_MADEIRA",
            "Atlantic/Reykjavik": "ATLANTIC_REYKJAVIK",
            "Atlantic/South_Georgia": "ATLANTIC_SOUTH_GEORGIA",
            "Atlantic/St_Helena": "ATLANTIC_ST_HELENA",
            "Atlantic/Stanley": "ATLANTIC_STANLEY",
            "Australia/Adelaide": "AUSTRALIA_ADELAIDE",
            "Australia/Brisbane": "AUSTRALIA_BRISBANE",
            "Australia/Broken_Hill": "AUSTRALIA_BROKEN_HILL",
            "Australia/Currie": "AUSTRALIA_CURRIE",
            "Australia/Darwin": "AUSTRALIA_DARWIN",
            "Australia/Eucla": "AUSTRALIA_EUCLA",
            "Australia/Hobart": "AUSTRALIA_HOBART",
            "Australia/Lindeman": "AUSTRALIA_LINDEMAN",
            "Australia/Lord_Howe": "AUSTRALIA_LORD_HOWE",
            "Australia/Melbourne": "AUSTRALIA_MELBOURNE",
            "Australia/Perth": "AUSTRALIA_PERTH",
            "Australia/Sydney": "AUSTRALIA_SYDNEY",
            "Canada/Atlantic": "CANADA_ATLANTIC",
            "Canada/Central": "CANADA_CENTRAL",
            "Canada/Eastern": "CANADA_EASTERN",
            "Canada/Mountain": "CANADA_MOUNTAIN",
            "Canada/Newfoundland": "CANADA_NEWFOUNDLAND",
            "Canada/Pacific": "CANADA_PACIFIC",
            "Europe/Amsterdam": "EUROPE_AMSTERDAM",
            "Europe/Andorra": "EUROPE_ANDORRA",
            "Europe/Astrakhan": "EUROPE_ASTRAKHAN",
            "Europe/Athens": "EUROPE_ATHENS",
            "Europe/Belgrade": "EUROPE_BELGRADE",
            "Europe/Berlin": "EUROPE_BERLIN",
            "Europe/Bratislava": "EUROPE_BRATISLAVA",
            "Europe/Brussels": "EUROPE_BRUSSELS",
            "Europe/Bucharest": "EUROPE_BUCHAREST",
            "Europe/Budapest": "EUROPE_BUDAPEST",
            "Europe/Busingen": "EUROPE_BUSINGEN",
            "Europe/Chisinau": "EUROPE_CHISINAU",
            "Europe/Copenhagen": "EUROPE_COPENHAGEN",
            "Europe/Dublin": "EUROPE_DUBLIN",
            "Europe/Gibraltar": "EUROPE_GIBRALTAR",
            "Europe/Guernsey": "EUROPE_GUERNSEY",
            "Europe/Helsinki": "EUROPE_HELSINKI",
            "Europe/Isle_of_Man": "EUROPE_ISLE_OF_MAN",
            "Europe/Istanbul": "EUROPE_ISTANBUL",
            "Europe/Jersey": "EUROPE_JERSEY",
            "Europe/Kaliningrad": "EUROPE_KALININGRAD",
            "Europe/Kiev": "EUROPE_KIEV",
            "Europe/Kirov": "EUROPE_KIROV",
            "Europe/Lisbon": "EUROPE_LISBON",
            "Europe/Ljubljana": "EUROPE_LJUBLJANA",
            "Europe/London": "EUROPE_LONDON",
            "Europe/Luxembourg": "EUROPE_LUXEMBOURG",
            "Europe/Madrid": "EUROPE_MADRID",
            "Europe/Malta": "EUROPE_MALTA",
            "Europe/Mariehamn": "EUROPE_MARIEHAMN",
            "Europe/Minsk": "EUROPE_MINSK",
            "Europe/Monaco": "EUROPE_MONACO",
            "Europe/Moscow": "EUROPE_MOSCOW",
            "Europe/Oslo": "EUROPE_OSLO",
            "Europe/Paris": "EUROPE_PARIS",
            "Europe/Podgorica": "EUROPE_PODGORICA",
            "Europe/Prague": "EUROPE_PRAGUE",
            "Europe/Riga": "EUROPE_RIGA",
            "Europe/Rome": "EUROPE_ROME",
            "Europe/Samara": "EUROPE_SAMARA",
            "Europe/San_Marino": "EUROPE_SAN_MARINO",
            "Europe/Sarajevo": "EUROPE_SARAJEVO",
            "Europe/Saratov": "EUROPE_SARATOV",
            "Europe/Simferopol": "EUROPE_SIMFEROPOL",
            "Europe/Skopje": "EUROPE_SKOPJE",
            "Europe/Sofia": "EUROPE_SOFIA",
            "Europe/Stockholm": "EUROPE_STOCKHOLM",
            "Europe/Tallinn": "EUROPE_TALLINN",
            "Europe/Tirane": "EUROPE_TIRANE",
            "Europe/Ulyanovsk": "EUROPE_ULYANOVSK",
            "Europe/Uzhgorod": "EUROPE_UZHGOROD",
            "Europe/Vaduz": "EUROPE_VADUZ",
            "Europe/Vatican": "EUROPE_VATICAN",
            "Europe/Vienna": "EUROPE_VIENNA",
            "Europe/Vilnius": "EUROPE_VILNIUS",
            "Europe/Volgograd": "EUROPE_VOLGOGRAD",
            "Europe/Warsaw": "EUROPE_WARSAW",
            "Europe/Zagreb": "EUROPE_ZAGREB",
            "Europe/Zaporozhye": "EUROPE_ZAPOROZHYE",
            "Europe/Zurich": "EUROPE_ZURICH",
            "GMT": "GMT",
            "Indian/Antananarivo": "INDIAN_ANTANANARIVO",
            "Indian/Chagos": "INDIAN_CHAGOS",
            "Indian/Christmas": "INDIAN_CHRISTMAS",
            "Indian/Cocos": "INDIAN_COCOS",
            "Indian/Comoro": "INDIAN_COMORO",
            "Indian/Kerguelen": "INDIAN_KERGUELEN",
            "Indian/Mahe": "INDIAN_MAHE",
            "Indian/Maldives": "INDIAN_MALDIVES",
            "Indian/Mauritius": "INDIAN_MAURITIUS",
            "Indian/Mayotte": "INDIAN_MAYOTTE",
            "Indian/Reunion": "INDIAN_REUNION",
            "Pacific/Apia": "PACIFIC_APIA",
            "Pacific/Auckland": "PACIFIC_AUCKLAND",
            "Pacific/Bougainville": "PACIFIC_BOUGAINVILLE",
            "Pacific/Chatham": "PACIFIC_CHATHAM",
            "Pacific/Chuuk": "PACIFIC_CHUUK",
            "Pacific/Easter": "PACIFIC_EASTER",
            "Pacific/Efate": "PACIFIC_EFATE",
            "Pacific/Enderbury": "PACIFIC_ENDERBURY",
            "Pacific/Fakaofo": "PACIFIC_FAKAOFO",
            "Pacific/Fiji": "PACIFIC_FIJI",
            "Pacific/Funafuti": "PACIFIC_FUNAFUTI",
            "Pacific/Galapagos": "PACIFIC_GALAPAGOS",
            "Pacific/Gambier": "PACIFIC_GAMBIER",
            "Pacific/Guadalcanal": "PACIFIC_GUADALCANAL",
            "Pacific/Guam": "PACIFIC_GUAM",
            "Pacific/Honolulu": "PACIFIC_HONOLULU",
            "Pacific/Kiritimati": "PACIFIC_KIRITIMATI",
            "Pacific/Kosrae": "PACIFIC_KOSRAE",
            "Pacific/Kwajalein": "PACIFIC_KWAJALEIN",
            "Pacific/Majuro": "PACIFIC_MAJURO",
            "Pacific/Marquesas": "PACIFIC_MARQUESAS",
            "Pacific/Midway": "PACIFIC_MIDWAY",
            "Pacific/Nauru": "PACIFIC_NAURU",
            "Pacific/Niue": "PACIFIC_NIUE",
            "Pacific/Norfolk": "PACIFIC_NORFOLK",
            "Pacific/Noumea": "PACIFIC_NOUMEA",
            "Pacific/Pago_Pago": "PACIFIC_PAGO_PAGO",
            "Pacific/Palau": "PACIFIC_PALAU",
            "Pacific/Pitcairn": "PACIFIC_PITCAIRN",
            "Pacific/Pohnpei": "PACIFIC_POHNPEI",
            "Pacific/Port_Moresby": "PACIFIC_PORT_MORESBY",
            "Pacific/Rarotonga": "PACIFIC_RAROTONGA",
            "Pacific/Saipan": "PACIFIC_SAIPAN",
            "Pacific/Tahiti": "PACIFIC_TAHITI",
            "Pacific/Tarawa": "PACIFIC_TARAWA",
            "Pacific/Tongatapu": "PACIFIC_TONGATAPU",
            "Pacific/Wake": "PACIFIC_WAKE",
            "Pacific/Wallis": "PACIFIC_WALLIS",
            "US/Alaska": "US_ALASKA",
            "US/Arizona": "US_ARIZONA",
            "US/Central": "US_CENTRAL",
            "US/Eastern": "US_EASTERN",
            "US/Hawaii": "US_HAWAII",
            "US/Mountain": "US_MOUNTAIN",
            "US/Pacific": "US_PACIFIC",
            "UTC": "UTC",
        }
    
    @schemas.classproperty
    def AFRICA_ABIDJAN(cls):
        return cls("Africa/Abidjan")
    
    @schemas.classproperty
    def AFRICA_ACCRA(cls):
        return cls("Africa/Accra")
    
    @schemas.classproperty
    def AFRICA_ADDIS_ABABA(cls):
        return cls("Africa/Addis_Ababa")
    
    @schemas.classproperty
    def AFRICA_ALGIERS(cls):
        return cls("Africa/Algiers")
    
    @schemas.classproperty
    def AFRICA_ASMARA(cls):
        return cls("Africa/Asmara")
    
    @schemas.classproperty
    def AFRICA_BAMAKO(cls):
        return cls("Africa/Bamako")
    
    @schemas.classproperty
    def AFRICA_BANGUI(cls):
        return cls("Africa/Bangui")
    
    @schemas.classproperty
    def AFRICA_BANJUL(cls):
        return cls("Africa/Banjul")
    
    @schemas.classproperty
    def AFRICA_BISSAU(cls):
        return cls("Africa/Bissau")
    
    @schemas.classproperty
    def AFRICA_BLANTYRE(cls):
        return cls("Africa/Blantyre")
    
    @schemas.classproperty
    def AFRICA_BRAZZAVILLE(cls):
        return cls("Africa/Brazzaville")
    
    @schemas.classproperty
    def AFRICA_BUJUMBURA(cls):
        return cls("Africa/Bujumbura")
    
    @schemas.classproperty
    def AFRICA_CAIRO(cls):
        return cls("Africa/Cairo")
    
    @schemas.classproperty
    def AFRICA_CASABLANCA(cls):
        return cls("Africa/Casablanca")
    
    @schemas.classproperty
    def AFRICA_CEUTA(cls):
        return cls("Africa/Ceuta")
    
    @schemas.classproperty
    def AFRICA_CONAKRY(cls):
        return cls("Africa/Conakry")
    
    @schemas.classproperty
    def AFRICA_DAKAR(cls):
        return cls("Africa/Dakar")
    
    @schemas.classproperty
    def AFRICA_DAR_ES_SALAAM(cls):
        return cls("Africa/Dar_es_Salaam")
    
    @schemas.classproperty
    def AFRICA_DJIBOUTI(cls):
        return cls("Africa/Djibouti")
    
    @schemas.classproperty
    def AFRICA_DOUALA(cls):
        return cls("Africa/Douala")
    
    @schemas.classproperty
    def AFRICA_EL_AAIUN(cls):
        return cls("Africa/El_Aaiun")
    
    @schemas.classproperty
    def AFRICA_FREETOWN(cls):
        return cls("Africa/Freetown")
    
    @schemas.classproperty
    def AFRICA_GABORONE(cls):
        return cls("Africa/Gaborone")
    
    @schemas.classproperty
    def AFRICA_HARARE(cls):
        return cls("Africa/Harare")
    
    @schemas.classproperty
    def AFRICA_JOHANNESBURG(cls):
        return cls("Africa/Johannesburg")
    
    @schemas.classproperty
    def AFRICA_JUBA(cls):
        return cls("Africa/Juba")
    
    @schemas.classproperty
    def AFRICA_KAMPALA(cls):
        return cls("Africa/Kampala")
    
    @schemas.classproperty
    def AFRICA_KHARTOUM(cls):
        return cls("Africa/Khartoum")
    
    @schemas.classproperty
    def AFRICA_KIGALI(cls):
        return cls("Africa/Kigali")
    
    @schemas.classproperty
    def AFRICA_KINSHASA(cls):
        return cls("Africa/Kinshasa")
    
    @schemas.classproperty
    def AFRICA_LAGOS(cls):
        return cls("Africa/Lagos")
    
    @schemas.classproperty
    def AFRICA_LIBREVILLE(cls):
        return cls("Africa/Libreville")
    
    @schemas.classproperty
    def AFRICA_LOME(cls):
        return cls("Africa/Lome")
    
    @schemas.classproperty
    def AFRICA_LUANDA(cls):
        return cls("Africa/Luanda")
    
    @schemas.classproperty
    def AFRICA_LUBUMBASHI(cls):
        return cls("Africa/Lubumbashi")
    
    @schemas.classproperty
    def AFRICA_LUSAKA(cls):
        return cls("Africa/Lusaka")
    
    @schemas.classproperty
    def AFRICA_MALABO(cls):
        return cls("Africa/Malabo")
    
    @schemas.classproperty
    def AFRICA_MAPUTO(cls):
        return cls("Africa/Maputo")
    
    @schemas.classproperty
    def AFRICA_MASERU(cls):
        return cls("Africa/Maseru")
    
    @schemas.classproperty
    def AFRICA_MBABANE(cls):
        return cls("Africa/Mbabane")
    
    @schemas.classproperty
    def AFRICA_MOGADISHU(cls):
        return cls("Africa/Mogadishu")
    
    @schemas.classproperty
    def AFRICA_MONROVIA(cls):
        return cls("Africa/Monrovia")
    
    @schemas.classproperty
    def AFRICA_NAIROBI(cls):
        return cls("Africa/Nairobi")
    
    @schemas.classproperty
    def AFRICA_NDJAMENA(cls):
        return cls("Africa/Ndjamena")
    
    @schemas.classproperty
    def AFRICA_NIAMEY(cls):
        return cls("Africa/Niamey")
    
    @schemas.classproperty
    def AFRICA_NOUAKCHOTT(cls):
        return cls("Africa/Nouakchott")
    
    @schemas.classproperty
    def AFRICA_OUAGADOUGOU(cls):
        return cls("Africa/Ouagadougou")
    
    @schemas.classproperty
    def AFRICA_PORTONOVO(cls):
        return cls("Africa/Porto-Novo")
    
    @schemas.classproperty
    def AFRICA_SAO_TOME(cls):
        return cls("Africa/Sao_Tome")
    
    @schemas.classproperty
    def AFRICA_TRIPOLI(cls):
        return cls("Africa/Tripoli")
    
    @schemas.classproperty
    def AFRICA_TUNIS(cls):
        return cls("Africa/Tunis")
    
    @schemas.classproperty
    def AFRICA_WINDHOEK(cls):
        return cls("Africa/Windhoek")
    
    @schemas.classproperty
    def AMERICA_ADAK(cls):
        return cls("America/Adak")
    
    @schemas.classproperty
    def AMERICA_ANCHORAGE(cls):
        return cls("America/Anchorage")
    
    @schemas.classproperty
    def AMERICA_ANGUILLA(cls):
        return cls("America/Anguilla")
    
    @schemas.classproperty
    def AMERICA_ANTIGUA(cls):
        return cls("America/Antigua")
    
    @schemas.classproperty
    def AMERICA_ARAGUAINA(cls):
        return cls("America/Araguaina")
    
    @schemas.classproperty
    def AMERICA_ARGENTINA_BUENOS_AIRES(cls):
        return cls("America/Argentina/Buenos_Aires")
    
    @schemas.classproperty
    def AMERICA_ARGENTINA_CATAMARCA(cls):
        return cls("America/Argentina/Catamarca")
    
    @schemas.classproperty
    def AMERICA_ARGENTINA_CORDOBA(cls):
        return cls("America/Argentina/Cordoba")
    
    @schemas.classproperty
    def AMERICA_ARGENTINA_JUJUY(cls):
        return cls("America/Argentina/Jujuy")
    
    @schemas.classproperty
    def AMERICA_ARGENTINA_LA_RIOJA(cls):
        return cls("America/Argentina/La_Rioja")
    
    @schemas.classproperty
    def AMERICA_ARGENTINA_MENDOZA(cls):
        return cls("America/Argentina/Mendoza")
    
    @schemas.classproperty
    def AMERICA_ARGENTINA_RIO_GALLEGOS(cls):
        return cls("America/Argentina/Rio_Gallegos")
    
    @schemas.classproperty
    def AMERICA_ARGENTINA_SALTA(cls):
        return cls("America/Argentina/Salta")
    
    @schemas.classproperty
    def AMERICA_ARGENTINA_SAN_JUAN(cls):
        return cls("America/Argentina/San_Juan")
    
    @schemas.classproperty
    def AMERICA_ARGENTINA_SAN_LUIS(cls):
        return cls("America/Argentina/San_Luis")
    
    @schemas.classproperty
    def AMERICA_ARGENTINA_TUCUMAN(cls):
        return cls("America/Argentina/Tucuman")
    
    @schemas.classproperty
    def AMERICA_ARGENTINA_USHUAIA(cls):
        return cls("America/Argentina/Ushuaia")
    
    @schemas.classproperty
    def AMERICA_ARUBA(cls):
        return cls("America/Aruba")
    
    @schemas.classproperty
    def AMERICA_ASUNCION(cls):
        return cls("America/Asuncion")
    
    @schemas.classproperty
    def AMERICA_ATIKOKAN(cls):
        return cls("America/Atikokan")
    
    @schemas.classproperty
    def AMERICA_BAHIA(cls):
        return cls("America/Bahia")
    
    @schemas.classproperty
    def AMERICA_BAHIA_BANDERAS(cls):
        return cls("America/Bahia_Banderas")
    
    @schemas.classproperty
    def AMERICA_BARBADOS(cls):
        return cls("America/Barbados")
    
    @schemas.classproperty
    def AMERICA_BELEM(cls):
        return cls("America/Belem")
    
    @schemas.classproperty
    def AMERICA_BELIZE(cls):
        return cls("America/Belize")
    
    @schemas.classproperty
    def AMERICA_BLANCSABLON(cls):
        return cls("America/Blanc-Sablon")
    
    @schemas.classproperty
    def AMERICA_BOA_VISTA(cls):
        return cls("America/Boa_Vista")
    
    @schemas.classproperty
    def AMERICA_BOGOTA(cls):
        return cls("America/Bogota")
    
    @schemas.classproperty
    def AMERICA_BOISE(cls):
        return cls("America/Boise")
    
    @schemas.classproperty
    def AMERICA_CAMBRIDGE_BAY(cls):
        return cls("America/Cambridge_Bay")
    
    @schemas.classproperty
    def AMERICA_CAMPO_GRANDE(cls):
        return cls("America/Campo_Grande")
    
    @schemas.classproperty
    def AMERICA_CANCUN(cls):
        return cls("America/Cancun")
    
    @schemas.classproperty
    def AMERICA_CARACAS(cls):
        return cls("America/Caracas")
    
    @schemas.classproperty
    def AMERICA_CAYENNE(cls):
        return cls("America/Cayenne")
    
    @schemas.classproperty
    def AMERICA_CAYMAN(cls):
        return cls("America/Cayman")
    
    @schemas.classproperty
    def AMERICA_CHICAGO(cls):
        return cls("America/Chicago")
    
    @schemas.classproperty
    def AMERICA_CHIHUAHUA(cls):
        return cls("America/Chihuahua")
    
    @schemas.classproperty
    def AMERICA_COSTA_RICA(cls):
        return cls("America/Costa_Rica")
    
    @schemas.classproperty
    def AMERICA_CRESTON(cls):
        return cls("America/Creston")
    
    @schemas.classproperty
    def AMERICA_CUIABA(cls):
        return cls("America/Cuiaba")
    
    @schemas.classproperty
    def AMERICA_CURACAO(cls):
        return cls("America/Curacao")
    
    @schemas.classproperty
    def AMERICA_DANMARKSHAVN(cls):
        return cls("America/Danmarkshavn")
    
    @schemas.classproperty
    def AMERICA_DAWSON(cls):
        return cls("America/Dawson")
    
    @schemas.classproperty
    def AMERICA_DAWSON_CREEK(cls):
        return cls("America/Dawson_Creek")
    
    @schemas.classproperty
    def AMERICA_DENVER(cls):
        return cls("America/Denver")
    
    @schemas.classproperty
    def AMERICA_DETROIT(cls):
        return cls("America/Detroit")
    
    @schemas.classproperty
    def AMERICA_DOMINICA(cls):
        return cls("America/Dominica")
    
    @schemas.classproperty
    def AMERICA_EDMONTON(cls):
        return cls("America/Edmonton")
    
    @schemas.classproperty
    def AMERICA_EIRUNEPE(cls):
        return cls("America/Eirunepe")
    
    @schemas.classproperty
    def AMERICA_EL_SALVADOR(cls):
        return cls("America/El_Salvador")
    
    @schemas.classproperty
    def AMERICA_FORT_NELSON(cls):
        return cls("America/Fort_Nelson")
    
    @schemas.classproperty
    def AMERICA_FORTALEZA(cls):
        return cls("America/Fortaleza")
    
    @schemas.classproperty
    def AMERICA_GLACE_BAY(cls):
        return cls("America/Glace_Bay")
    
    @schemas.classproperty
    def AMERICA_GODTHAB(cls):
        return cls("America/Godthab")
    
    @schemas.classproperty
    def AMERICA_GOOSE_BAY(cls):
        return cls("America/Goose_Bay")
    
    @schemas.classproperty
    def AMERICA_GRAND_TURK(cls):
        return cls("America/Grand_Turk")
    
    @schemas.classproperty
    def AMERICA_GRENADA(cls):
        return cls("America/Grenada")
    
    @schemas.classproperty
    def AMERICA_GUADELOUPE(cls):
        return cls("America/Guadeloupe")
    
    @schemas.classproperty
    def AMERICA_GUATEMALA(cls):
        return cls("America/Guatemala")
    
    @schemas.classproperty
    def AMERICA_GUAYAQUIL(cls):
        return cls("America/Guayaquil")
    
    @schemas.classproperty
    def AMERICA_GUYANA(cls):
        return cls("America/Guyana")
    
    @schemas.classproperty
    def AMERICA_HALIFAX(cls):
        return cls("America/Halifax")
    
    @schemas.classproperty
    def AMERICA_HAVANA(cls):
        return cls("America/Havana")
    
    @schemas.classproperty
    def AMERICA_HERMOSILLO(cls):
        return cls("America/Hermosillo")
    
    @schemas.classproperty
    def AMERICA_INDIANA_INDIANAPOLIS(cls):
        return cls("America/Indiana/Indianapolis")
    
    @schemas.classproperty
    def AMERICA_INDIANA_KNOX(cls):
        return cls("America/Indiana/Knox")
    
    @schemas.classproperty
    def AMERICA_INDIANA_MARENGO(cls):
        return cls("America/Indiana/Marengo")
    
    @schemas.classproperty
    def AMERICA_INDIANA_PETERSBURG(cls):
        return cls("America/Indiana/Petersburg")
    
    @schemas.classproperty
    def AMERICA_INDIANA_TELL_CITY(cls):
        return cls("America/Indiana/Tell_City")
    
    @schemas.classproperty
    def AMERICA_INDIANA_VEVAY(cls):
        return cls("America/Indiana/Vevay")
    
    @schemas.classproperty
    def AMERICA_INDIANA_VINCENNES(cls):
        return cls("America/Indiana/Vincennes")
    
    @schemas.classproperty
    def AMERICA_INDIANA_WINAMAC(cls):
        return cls("America/Indiana/Winamac")
    
    @schemas.classproperty
    def AMERICA_INUVIK(cls):
        return cls("America/Inuvik")
    
    @schemas.classproperty
    def AMERICA_IQALUIT(cls):
        return cls("America/Iqaluit")
    
    @schemas.classproperty
    def AMERICA_JAMAICA(cls):
        return cls("America/Jamaica")
    
    @schemas.classproperty
    def AMERICA_JUNEAU(cls):
        return cls("America/Juneau")
    
    @schemas.classproperty
    def AMERICA_KENTUCKY_LOUISVILLE(cls):
        return cls("America/Kentucky/Louisville")
    
    @schemas.classproperty
    def AMERICA_KENTUCKY_MONTICELLO(cls):
        return cls("America/Kentucky/Monticello")
    
    @schemas.classproperty
    def AMERICA_KRALENDIJK(cls):
        return cls("America/Kralendijk")
    
    @schemas.classproperty
    def AMERICA_LA_PAZ(cls):
        return cls("America/La_Paz")
    
    @schemas.classproperty
    def AMERICA_LIMA(cls):
        return cls("America/Lima")
    
    @schemas.classproperty
    def AMERICA_LOS_ANGELES(cls):
        return cls("America/Los_Angeles")
    
    @schemas.classproperty
    def AMERICA_LOWER_PRINCES(cls):
        return cls("America/Lower_Princes")
    
    @schemas.classproperty
    def AMERICA_MACEIO(cls):
        return cls("America/Maceio")
    
    @schemas.classproperty
    def AMERICA_MANAGUA(cls):
        return cls("America/Managua")
    
    @schemas.classproperty
    def AMERICA_MANAUS(cls):
        return cls("America/Manaus")
    
    @schemas.classproperty
    def AMERICA_MARIGOT(cls):
        return cls("America/Marigot")
    
    @schemas.classproperty
    def AMERICA_MARTINIQUE(cls):
        return cls("America/Martinique")
    
    @schemas.classproperty
    def AMERICA_MATAMOROS(cls):
        return cls("America/Matamoros")
    
    @schemas.classproperty
    def AMERICA_MAZATLAN(cls):
        return cls("America/Mazatlan")
    
    @schemas.classproperty
    def AMERICA_MENOMINEE(cls):
        return cls("America/Menominee")
    
    @schemas.classproperty
    def AMERICA_MERIDA(cls):
        return cls("America/Merida")
    
    @schemas.classproperty
    def AMERICA_METLAKATLA(cls):
        return cls("America/Metlakatla")
    
    @schemas.classproperty
    def AMERICA_MEXICO_CITY(cls):
        return cls("America/Mexico_City")
    
    @schemas.classproperty
    def AMERICA_MIQUELON(cls):
        return cls("America/Miquelon")
    
    @schemas.classproperty
    def AMERICA_MONCTON(cls):
        return cls("America/Moncton")
    
    @schemas.classproperty
    def AMERICA_MONTERREY(cls):
        return cls("America/Monterrey")
    
    @schemas.classproperty
    def AMERICA_MONTEVIDEO(cls):
        return cls("America/Montevideo")
    
    @schemas.classproperty
    def AMERICA_MONTSERRAT(cls):
        return cls("America/Montserrat")
    
    @schemas.classproperty
    def AMERICA_NASSAU(cls):
        return cls("America/Nassau")
    
    @schemas.classproperty
    def AMERICA_NEW_YORK(cls):
        return cls("America/New_York")
    
    @schemas.classproperty
    def AMERICA_NIPIGON(cls):
        return cls("America/Nipigon")
    
    @schemas.classproperty
    def AMERICA_NOME(cls):
        return cls("America/Nome")
    
    @schemas.classproperty
    def AMERICA_NORONHA(cls):
        return cls("America/Noronha")
    
    @schemas.classproperty
    def AMERICA_NORTH_DAKOTA_BEULAH(cls):
        return cls("America/North_Dakota/Beulah")
    
    @schemas.classproperty
    def AMERICA_NORTH_DAKOTA_CENTER(cls):
        return cls("America/North_Dakota/Center")
    
    @schemas.classproperty
    def AMERICA_NORTH_DAKOTA_NEW_SALEM(cls):
        return cls("America/North_Dakota/New_Salem")
    
    @schemas.classproperty
    def AMERICA_OJINAGA(cls):
        return cls("America/Ojinaga")
    
    @schemas.classproperty
    def AMERICA_PANAMA(cls):
        return cls("America/Panama")
    
    @schemas.classproperty
    def AMERICA_PANGNIRTUNG(cls):
        return cls("America/Pangnirtung")
    
    @schemas.classproperty
    def AMERICA_PARAMARIBO(cls):
        return cls("America/Paramaribo")
    
    @schemas.classproperty
    def AMERICA_PHOENIX(cls):
        return cls("America/Phoenix")
    
    @schemas.classproperty
    def AMERICA_PORTAUPRINCE(cls):
        return cls("America/Port-au-Prince")
    
    @schemas.classproperty
    def AMERICA_PORT_OF_SPAIN(cls):
        return cls("America/Port_of_Spain")
    
    @schemas.classproperty
    def AMERICA_PORTO_VELHO(cls):
        return cls("America/Porto_Velho")
    
    @schemas.classproperty
    def AMERICA_PUERTO_RICO(cls):
        return cls("America/Puerto_Rico")
    
    @schemas.classproperty
    def AMERICA_PUNTA_ARENAS(cls):
        return cls("America/Punta_Arenas")
    
    @schemas.classproperty
    def AMERICA_RAINY_RIVER(cls):
        return cls("America/Rainy_River")
    
    @schemas.classproperty
    def AMERICA_RANKIN_INLET(cls):
        return cls("America/Rankin_Inlet")
    
    @schemas.classproperty
    def AMERICA_RECIFE(cls):
        return cls("America/Recife")
    
    @schemas.classproperty
    def AMERICA_REGINA(cls):
        return cls("America/Regina")
    
    @schemas.classproperty
    def AMERICA_RESOLUTE(cls):
        return cls("America/Resolute")
    
    @schemas.classproperty
    def AMERICA_RIO_BRANCO(cls):
        return cls("America/Rio_Branco")
    
    @schemas.classproperty
    def AMERICA_SANTAREM(cls):
        return cls("America/Santarem")
    
    @schemas.classproperty
    def AMERICA_SANTIAGO(cls):
        return cls("America/Santiago")
    
    @schemas.classproperty
    def AMERICA_SANTO_DOMINGO(cls):
        return cls("America/Santo_Domingo")
    
    @schemas.classproperty
    def AMERICA_SAO_PAULO(cls):
        return cls("America/Sao_Paulo")
    
    @schemas.classproperty
    def AMERICA_SCORESBYSUND(cls):
        return cls("America/Scoresbysund")
    
    @schemas.classproperty
    def AMERICA_SITKA(cls):
        return cls("America/Sitka")
    
    @schemas.classproperty
    def AMERICA_ST_BARTHELEMY(cls):
        return cls("America/St_Barthelemy")
    
    @schemas.classproperty
    def AMERICA_ST_JOHNS(cls):
        return cls("America/St_Johns")
    
    @schemas.classproperty
    def AMERICA_ST_KITTS(cls):
        return cls("America/St_Kitts")
    
    @schemas.classproperty
    def AMERICA_ST_LUCIA(cls):
        return cls("America/St_Lucia")
    
    @schemas.classproperty
    def AMERICA_ST_THOMAS(cls):
        return cls("America/St_Thomas")
    
    @schemas.classproperty
    def AMERICA_ST_VINCENT(cls):
        return cls("America/St_Vincent")
    
    @schemas.classproperty
    def AMERICA_SWIFT_CURRENT(cls):
        return cls("America/Swift_Current")
    
    @schemas.classproperty
    def AMERICA_TEGUCIGALPA(cls):
        return cls("America/Tegucigalpa")
    
    @schemas.classproperty
    def AMERICA_THULE(cls):
        return cls("America/Thule")
    
    @schemas.classproperty
    def AMERICA_THUNDER_BAY(cls):
        return cls("America/Thunder_Bay")
    
    @schemas.classproperty
    def AMERICA_TIJUANA(cls):
        return cls("America/Tijuana")
    
    @schemas.classproperty
    def AMERICA_TORONTO(cls):
        return cls("America/Toronto")
    
    @schemas.classproperty
    def AMERICA_TORTOLA(cls):
        return cls("America/Tortola")
    
    @schemas.classproperty
    def AMERICA_VANCOUVER(cls):
        return cls("America/Vancouver")
    
    @schemas.classproperty
    def AMERICA_WHITEHORSE(cls):
        return cls("America/Whitehorse")
    
    @schemas.classproperty
    def AMERICA_WINNIPEG(cls):
        return cls("America/Winnipeg")
    
    @schemas.classproperty
    def AMERICA_YAKUTAT(cls):
        return cls("America/Yakutat")
    
    @schemas.classproperty
    def AMERICA_YELLOWKNIFE(cls):
        return cls("America/Yellowknife")
    
    @schemas.classproperty
    def ANTARCTICA_CASEY(cls):
        return cls("Antarctica/Casey")
    
    @schemas.classproperty
    def ANTARCTICA_DAVIS(cls):
        return cls("Antarctica/Davis")
    
    @schemas.classproperty
    def ANTARCTICA_DUMONT_DURVILLE(cls):
        return cls("Antarctica/DumontDUrville")
    
    @schemas.classproperty
    def ANTARCTICA_MACQUARIE(cls):
        return cls("Antarctica/Macquarie")
    
    @schemas.classproperty
    def ANTARCTICA_MAWSON(cls):
        return cls("Antarctica/Mawson")
    
    @schemas.classproperty
    def ANTARCTICA_MC_MURDO(cls):
        return cls("Antarctica/McMurdo")
    
    @schemas.classproperty
    def ANTARCTICA_PALMER(cls):
        return cls("Antarctica/Palmer")
    
    @schemas.classproperty
    def ANTARCTICA_ROTHERA(cls):
        return cls("Antarctica/Rothera")
    
    @schemas.classproperty
    def ANTARCTICA_SYOWA(cls):
        return cls("Antarctica/Syowa")
    
    @schemas.classproperty
    def ANTARCTICA_TROLL(cls):
        return cls("Antarctica/Troll")
    
    @schemas.classproperty
    def ANTARCTICA_VOSTOK(cls):
        return cls("Antarctica/Vostok")
    
    @schemas.classproperty
    def ARCTIC_LONGYEARBYEN(cls):
        return cls("Arctic/Longyearbyen")
    
    @schemas.classproperty
    def ASIA_ADEN(cls):
        return cls("Asia/Aden")
    
    @schemas.classproperty
    def ASIA_ALMATY(cls):
        return cls("Asia/Almaty")
    
    @schemas.classproperty
    def ASIA_AMMAN(cls):
        return cls("Asia/Amman")
    
    @schemas.classproperty
    def ASIA_ANADYR(cls):
        return cls("Asia/Anadyr")
    
    @schemas.classproperty
    def ASIA_AQTAU(cls):
        return cls("Asia/Aqtau")
    
    @schemas.classproperty
    def ASIA_AQTOBE(cls):
        return cls("Asia/Aqtobe")
    
    @schemas.classproperty
    def ASIA_ASHGABAT(cls):
        return cls("Asia/Ashgabat")
    
    @schemas.classproperty
    def ASIA_ATYRAU(cls):
        return cls("Asia/Atyrau")
    
    @schemas.classproperty
    def ASIA_BAGHDAD(cls):
        return cls("Asia/Baghdad")
    
    @schemas.classproperty
    def ASIA_BAHRAIN(cls):
        return cls("Asia/Bahrain")
    
    @schemas.classproperty
    def ASIA_BAKU(cls):
        return cls("Asia/Baku")
    
    @schemas.classproperty
    def ASIA_BANGKOK(cls):
        return cls("Asia/Bangkok")
    
    @schemas.classproperty
    def ASIA_BARNAUL(cls):
        return cls("Asia/Barnaul")
    
    @schemas.classproperty
    def ASIA_BEIRUT(cls):
        return cls("Asia/Beirut")
    
    @schemas.classproperty
    def ASIA_BISHKEK(cls):
        return cls("Asia/Bishkek")
    
    @schemas.classproperty
    def ASIA_BRUNEI(cls):
        return cls("Asia/Brunei")
    
    @schemas.classproperty
    def ASIA_CHITA(cls):
        return cls("Asia/Chita")
    
    @schemas.classproperty
    def ASIA_CHOIBALSAN(cls):
        return cls("Asia/Choibalsan")
    
    @schemas.classproperty
    def ASIA_COLOMBO(cls):
        return cls("Asia/Colombo")
    
    @schemas.classproperty
    def ASIA_DAMASCUS(cls):
        return cls("Asia/Damascus")
    
    @schemas.classproperty
    def ASIA_DHAKA(cls):
        return cls("Asia/Dhaka")
    
    @schemas.classproperty
    def ASIA_DILI(cls):
        return cls("Asia/Dili")
    
    @schemas.classproperty
    def ASIA_DUBAI(cls):
        return cls("Asia/Dubai")
    
    @schemas.classproperty
    def ASIA_DUSHANBE(cls):
        return cls("Asia/Dushanbe")
    
    @schemas.classproperty
    def ASIA_FAMAGUSTA(cls):
        return cls("Asia/Famagusta")
    
    @schemas.classproperty
    def ASIA_GAZA(cls):
        return cls("Asia/Gaza")
    
    @schemas.classproperty
    def ASIA_HEBRON(cls):
        return cls("Asia/Hebron")
    
    @schemas.classproperty
    def ASIA_HO_CHI_MINH(cls):
        return cls("Asia/Ho_Chi_Minh")
    
    @schemas.classproperty
    def ASIA_HONG_KONG(cls):
        return cls("Asia/Hong_Kong")
    
    @schemas.classproperty
    def ASIA_HOVD(cls):
        return cls("Asia/Hovd")
    
    @schemas.classproperty
    def ASIA_IRKUTSK(cls):
        return cls("Asia/Irkutsk")
    
    @schemas.classproperty
    def ASIA_JAKARTA(cls):
        return cls("Asia/Jakarta")
    
    @schemas.classproperty
    def ASIA_JAYAPURA(cls):
        return cls("Asia/Jayapura")
    
    @schemas.classproperty
    def ASIA_JERUSALEM(cls):
        return cls("Asia/Jerusalem")
    
    @schemas.classproperty
    def ASIA_KABUL(cls):
        return cls("Asia/Kabul")
    
    @schemas.classproperty
    def ASIA_KAMCHATKA(cls):
        return cls("Asia/Kamchatka")
    
    @schemas.classproperty
    def ASIA_KARACHI(cls):
        return cls("Asia/Karachi")
    
    @schemas.classproperty
    def ASIA_KATHMANDU(cls):
        return cls("Asia/Kathmandu")
    
    @schemas.classproperty
    def ASIA_KHANDYGA(cls):
        return cls("Asia/Khandyga")
    
    @schemas.classproperty
    def ASIA_KOLKATA(cls):
        return cls("Asia/Kolkata")
    
    @schemas.classproperty
    def ASIA_KRASNOYARSK(cls):
        return cls("Asia/Krasnoyarsk")
    
    @schemas.classproperty
    def ASIA_KUALA_LUMPUR(cls):
        return cls("Asia/Kuala_Lumpur")
    
    @schemas.classproperty
    def ASIA_KUCHING(cls):
        return cls("Asia/Kuching")
    
    @schemas.classproperty
    def ASIA_KUWAIT(cls):
        return cls("Asia/Kuwait")
    
    @schemas.classproperty
    def ASIA_MACAU(cls):
        return cls("Asia/Macau")
    
    @schemas.classproperty
    def ASIA_MAGADAN(cls):
        return cls("Asia/Magadan")
    
    @schemas.classproperty
    def ASIA_MAKASSAR(cls):
        return cls("Asia/Makassar")
    
    @schemas.classproperty
    def ASIA_MANILA(cls):
        return cls("Asia/Manila")
    
    @schemas.classproperty
    def ASIA_MUSCAT(cls):
        return cls("Asia/Muscat")
    
    @schemas.classproperty
    def ASIA_NICOSIA(cls):
        return cls("Asia/Nicosia")
    
    @schemas.classproperty
    def ASIA_NOVOKUZNETSK(cls):
        return cls("Asia/Novokuznetsk")
    
    @schemas.classproperty
    def ASIA_NOVOSIBIRSK(cls):
        return cls("Asia/Novosibirsk")
    
    @schemas.classproperty
    def ASIA_OMSK(cls):
        return cls("Asia/Omsk")
    
    @schemas.classproperty
    def ASIA_ORAL(cls):
        return cls("Asia/Oral")
    
    @schemas.classproperty
    def ASIA_PHNOM_PENH(cls):
        return cls("Asia/Phnom_Penh")
    
    @schemas.classproperty
    def ASIA_PONTIANAK(cls):
        return cls("Asia/Pontianak")
    
    @schemas.classproperty
    def ASIA_PYONGYANG(cls):
        return cls("Asia/Pyongyang")
    
    @schemas.classproperty
    def ASIA_QATAR(cls):
        return cls("Asia/Qatar")
    
    @schemas.classproperty
    def ASIA_QYZYLORDA(cls):
        return cls("Asia/Qyzylorda")
    
    @schemas.classproperty
    def ASIA_RIYADH(cls):
        return cls("Asia/Riyadh")
    
    @schemas.classproperty
    def ASIA_SAKHALIN(cls):
        return cls("Asia/Sakhalin")
    
    @schemas.classproperty
    def ASIA_SAMARKAND(cls):
        return cls("Asia/Samarkand")
    
    @schemas.classproperty
    def ASIA_SEOUL(cls):
        return cls("Asia/Seoul")
    
    @schemas.classproperty
    def ASIA_SHANGHAI(cls):
        return cls("Asia/Shanghai")
    
    @schemas.classproperty
    def ASIA_SINGAPORE(cls):
        return cls("Asia/Singapore")
    
    @schemas.classproperty
    def ASIA_SREDNEKOLYMSK(cls):
        return cls("Asia/Srednekolymsk")
    
    @schemas.classproperty
    def ASIA_TAIPEI(cls):
        return cls("Asia/Taipei")
    
    @schemas.classproperty
    def ASIA_TASHKENT(cls):
        return cls("Asia/Tashkent")
    
    @schemas.classproperty
    def ASIA_TBILISI(cls):
        return cls("Asia/Tbilisi")
    
    @schemas.classproperty
    def ASIA_TEHRAN(cls):
        return cls("Asia/Tehran")
    
    @schemas.classproperty
    def ASIA_THIMPHU(cls):
        return cls("Asia/Thimphu")
    
    @schemas.classproperty
    def ASIA_TOKYO(cls):
        return cls("Asia/Tokyo")
    
    @schemas.classproperty
    def ASIA_TOMSK(cls):
        return cls("Asia/Tomsk")
    
    @schemas.classproperty
    def ASIA_ULAANBAATAR(cls):
        return cls("Asia/Ulaanbaatar")
    
    @schemas.classproperty
    def ASIA_URUMQI(cls):
        return cls("Asia/Urumqi")
    
    @schemas.classproperty
    def ASIA_USTNERA(cls):
        return cls("Asia/Ust-Nera")
    
    @schemas.classproperty
    def ASIA_VIENTIANE(cls):
        return cls("Asia/Vientiane")
    
    @schemas.classproperty
    def ASIA_VLADIVOSTOK(cls):
        return cls("Asia/Vladivostok")
    
    @schemas.classproperty
    def ASIA_YAKUTSK(cls):
        return cls("Asia/Yakutsk")
    
    @schemas.classproperty
    def ASIA_YANGON(cls):
        return cls("Asia/Yangon")
    
    @schemas.classproperty
    def ASIA_YEKATERINBURG(cls):
        return cls("Asia/Yekaterinburg")
    
    @schemas.classproperty
    def ASIA_YEREVAN(cls):
        return cls("Asia/Yerevan")
    
    @schemas.classproperty
    def ATLANTIC_AZORES(cls):
        return cls("Atlantic/Azores")
    
    @schemas.classproperty
    def ATLANTIC_BERMUDA(cls):
        return cls("Atlantic/Bermuda")
    
    @schemas.classproperty
    def ATLANTIC_CANARY(cls):
        return cls("Atlantic/Canary")
    
    @schemas.classproperty
    def ATLANTIC_CAPE_VERDE(cls):
        return cls("Atlantic/Cape_Verde")
    
    @schemas.classproperty
    def ATLANTIC_FAROE(cls):
        return cls("Atlantic/Faroe")
    
    @schemas.classproperty
    def ATLANTIC_MADEIRA(cls):
        return cls("Atlantic/Madeira")
    
    @schemas.classproperty
    def ATLANTIC_REYKJAVIK(cls):
        return cls("Atlantic/Reykjavik")
    
    @schemas.classproperty
    def ATLANTIC_SOUTH_GEORGIA(cls):
        return cls("Atlantic/South_Georgia")
    
    @schemas.classproperty
    def ATLANTIC_ST_HELENA(cls):
        return cls("Atlantic/St_Helena")
    
    @schemas.classproperty
    def ATLANTIC_STANLEY(cls):
        return cls("Atlantic/Stanley")
    
    @schemas.classproperty
    def AUSTRALIA_ADELAIDE(cls):
        return cls("Australia/Adelaide")
    
    @schemas.classproperty
    def AUSTRALIA_BRISBANE(cls):
        return cls("Australia/Brisbane")
    
    @schemas.classproperty
    def AUSTRALIA_BROKEN_HILL(cls):
        return cls("Australia/Broken_Hill")
    
    @schemas.classproperty
    def AUSTRALIA_CURRIE(cls):
        return cls("Australia/Currie")
    
    @schemas.classproperty
    def AUSTRALIA_DARWIN(cls):
        return cls("Australia/Darwin")
    
    @schemas.classproperty
    def AUSTRALIA_EUCLA(cls):
        return cls("Australia/Eucla")
    
    @schemas.classproperty
    def AUSTRALIA_HOBART(cls):
        return cls("Australia/Hobart")
    
    @schemas.classproperty
    def AUSTRALIA_LINDEMAN(cls):
        return cls("Australia/Lindeman")
    
    @schemas.classproperty
    def AUSTRALIA_LORD_HOWE(cls):
        return cls("Australia/Lord_Howe")
    
    @schemas.classproperty
    def AUSTRALIA_MELBOURNE(cls):
        return cls("Australia/Melbourne")
    
    @schemas.classproperty
    def AUSTRALIA_PERTH(cls):
        return cls("Australia/Perth")
    
    @schemas.classproperty
    def AUSTRALIA_SYDNEY(cls):
        return cls("Australia/Sydney")
    
    @schemas.classproperty
    def CANADA_ATLANTIC(cls):
        return cls("Canada/Atlantic")
    
    @schemas.classproperty
    def CANADA_CENTRAL(cls):
        return cls("Canada/Central")
    
    @schemas.classproperty
    def CANADA_EASTERN(cls):
        return cls("Canada/Eastern")
    
    @schemas.classproperty
    def CANADA_MOUNTAIN(cls):
        return cls("Canada/Mountain")
    
    @schemas.classproperty
    def CANADA_NEWFOUNDLAND(cls):
        return cls("Canada/Newfoundland")
    
    @schemas.classproperty
    def CANADA_PACIFIC(cls):
        return cls("Canada/Pacific")
    
    @schemas.classproperty
    def EUROPE_AMSTERDAM(cls):
        return cls("Europe/Amsterdam")
    
    @schemas.classproperty
    def EUROPE_ANDORRA(cls):
        return cls("Europe/Andorra")
    
    @schemas.classproperty
    def EUROPE_ASTRAKHAN(cls):
        return cls("Europe/Astrakhan")
    
    @schemas.classproperty
    def EUROPE_ATHENS(cls):
        return cls("Europe/Athens")
    
    @schemas.classproperty
    def EUROPE_BELGRADE(cls):
        return cls("Europe/Belgrade")
    
    @schemas.classproperty
    def EUROPE_BERLIN(cls):
        return cls("Europe/Berlin")
    
    @schemas.classproperty
    def EUROPE_BRATISLAVA(cls):
        return cls("Europe/Bratislava")
    
    @schemas.classproperty
    def EUROPE_BRUSSELS(cls):
        return cls("Europe/Brussels")
    
    @schemas.classproperty
    def EUROPE_BUCHAREST(cls):
        return cls("Europe/Bucharest")
    
    @schemas.classproperty
    def EUROPE_BUDAPEST(cls):
        return cls("Europe/Budapest")
    
    @schemas.classproperty
    def EUROPE_BUSINGEN(cls):
        return cls("Europe/Busingen")
    
    @schemas.classproperty
    def EUROPE_CHISINAU(cls):
        return cls("Europe/Chisinau")
    
    @schemas.classproperty
    def EUROPE_COPENHAGEN(cls):
        return cls("Europe/Copenhagen")
    
    @schemas.classproperty
    def EUROPE_DUBLIN(cls):
        return cls("Europe/Dublin")
    
    @schemas.classproperty
    def EUROPE_GIBRALTAR(cls):
        return cls("Europe/Gibraltar")
    
    @schemas.classproperty
    def EUROPE_GUERNSEY(cls):
        return cls("Europe/Guernsey")
    
    @schemas.classproperty
    def EUROPE_HELSINKI(cls):
        return cls("Europe/Helsinki")
    
    @schemas.classproperty
    def EUROPE_ISLE_OF_MAN(cls):
        return cls("Europe/Isle_of_Man")
    
    @schemas.classproperty
    def EUROPE_ISTANBUL(cls):
        return cls("Europe/Istanbul")
    
    @schemas.classproperty
    def EUROPE_JERSEY(cls):
        return cls("Europe/Jersey")
    
    @schemas.classproperty
    def EUROPE_KALININGRAD(cls):
        return cls("Europe/Kaliningrad")
    
    @schemas.classproperty
    def EUROPE_KIEV(cls):
        return cls("Europe/Kiev")
    
    @schemas.classproperty
    def EUROPE_KIROV(cls):
        return cls("Europe/Kirov")
    
    @schemas.classproperty
    def EUROPE_LISBON(cls):
        return cls("Europe/Lisbon")
    
    @schemas.classproperty
    def EUROPE_LJUBLJANA(cls):
        return cls("Europe/Ljubljana")
    
    @schemas.classproperty
    def EUROPE_LONDON(cls):
        return cls("Europe/London")
    
    @schemas.classproperty
    def EUROPE_LUXEMBOURG(cls):
        return cls("Europe/Luxembourg")
    
    @schemas.classproperty
    def EUROPE_MADRID(cls):
        return cls("Europe/Madrid")
    
    @schemas.classproperty
    def EUROPE_MALTA(cls):
        return cls("Europe/Malta")
    
    @schemas.classproperty
    def EUROPE_MARIEHAMN(cls):
        return cls("Europe/Mariehamn")
    
    @schemas.classproperty
    def EUROPE_MINSK(cls):
        return cls("Europe/Minsk")
    
    @schemas.classproperty
    def EUROPE_MONACO(cls):
        return cls("Europe/Monaco")
    
    @schemas.classproperty
    def EUROPE_MOSCOW(cls):
        return cls("Europe/Moscow")
    
    @schemas.classproperty
    def EUROPE_OSLO(cls):
        return cls("Europe/Oslo")
    
    @schemas.classproperty
    def EUROPE_PARIS(cls):
        return cls("Europe/Paris")
    
    @schemas.classproperty
    def EUROPE_PODGORICA(cls):
        return cls("Europe/Podgorica")
    
    @schemas.classproperty
    def EUROPE_PRAGUE(cls):
        return cls("Europe/Prague")
    
    @schemas.classproperty
    def EUROPE_RIGA(cls):
        return cls("Europe/Riga")
    
    @schemas.classproperty
    def EUROPE_ROME(cls):
        return cls("Europe/Rome")
    
    @schemas.classproperty
    def EUROPE_SAMARA(cls):
        return cls("Europe/Samara")
    
    @schemas.classproperty
    def EUROPE_SAN_MARINO(cls):
        return cls("Europe/San_Marino")
    
    @schemas.classproperty
    def EUROPE_SARAJEVO(cls):
        return cls("Europe/Sarajevo")
    
    @schemas.classproperty
    def EUROPE_SARATOV(cls):
        return cls("Europe/Saratov")
    
    @schemas.classproperty
    def EUROPE_SIMFEROPOL(cls):
        return cls("Europe/Simferopol")
    
    @schemas.classproperty
    def EUROPE_SKOPJE(cls):
        return cls("Europe/Skopje")
    
    @schemas.classproperty
    def EUROPE_SOFIA(cls):
        return cls("Europe/Sofia")
    
    @schemas.classproperty
    def EUROPE_STOCKHOLM(cls):
        return cls("Europe/Stockholm")
    
    @schemas.classproperty
    def EUROPE_TALLINN(cls):
        return cls("Europe/Tallinn")
    
    @schemas.classproperty
    def EUROPE_TIRANE(cls):
        return cls("Europe/Tirane")
    
    @schemas.classproperty
    def EUROPE_ULYANOVSK(cls):
        return cls("Europe/Ulyanovsk")
    
    @schemas.classproperty
    def EUROPE_UZHGOROD(cls):
        return cls("Europe/Uzhgorod")
    
    @schemas.classproperty
    def EUROPE_VADUZ(cls):
        return cls("Europe/Vaduz")
    
    @schemas.classproperty
    def EUROPE_VATICAN(cls):
        return cls("Europe/Vatican")
    
    @schemas.classproperty
    def EUROPE_VIENNA(cls):
        return cls("Europe/Vienna")
    
    @schemas.classproperty
    def EUROPE_VILNIUS(cls):
        return cls("Europe/Vilnius")
    
    @schemas.classproperty
    def EUROPE_VOLGOGRAD(cls):
        return cls("Europe/Volgograd")
    
    @schemas.classproperty
    def EUROPE_WARSAW(cls):
        return cls("Europe/Warsaw")
    
    @schemas.classproperty
    def EUROPE_ZAGREB(cls):
        return cls("Europe/Zagreb")
    
    @schemas.classproperty
    def EUROPE_ZAPOROZHYE(cls):
        return cls("Europe/Zaporozhye")
    
    @schemas.classproperty
    def EUROPE_ZURICH(cls):
        return cls("Europe/Zurich")
    
    @schemas.classproperty
    def GMT(cls):
        return cls("GMT")
    
    @schemas.classproperty
    def INDIAN_ANTANANARIVO(cls):
        return cls("Indian/Antananarivo")
    
    @schemas.classproperty
    def INDIAN_CHAGOS(cls):
        return cls("Indian/Chagos")
    
    @schemas.classproperty
    def INDIAN_CHRISTMAS(cls):
        return cls("Indian/Christmas")
    
    @schemas.classproperty
    def INDIAN_COCOS(cls):
        return cls("Indian/Cocos")
    
    @schemas.classproperty
    def INDIAN_COMORO(cls):
        return cls("Indian/Comoro")
    
    @schemas.classproperty
    def INDIAN_KERGUELEN(cls):
        return cls("Indian/Kerguelen")
    
    @schemas.classproperty
    def INDIAN_MAHE(cls):
        return cls("Indian/Mahe")
    
    @schemas.classproperty
    def INDIAN_MALDIVES(cls):
        return cls("Indian/Maldives")
    
    @schemas.classproperty
    def INDIAN_MAURITIUS(cls):
        return cls("Indian/Mauritius")
    
    @schemas.classproperty
    def INDIAN_MAYOTTE(cls):
        return cls("Indian/Mayotte")
    
    @schemas.classproperty
    def INDIAN_REUNION(cls):
        return cls("Indian/Reunion")
    
    @schemas.classproperty
    def PACIFIC_APIA(cls):
        return cls("Pacific/Apia")
    
    @schemas.classproperty
    def PACIFIC_AUCKLAND(cls):
        return cls("Pacific/Auckland")
    
    @schemas.classproperty
    def PACIFIC_BOUGAINVILLE(cls):
        return cls("Pacific/Bougainville")
    
    @schemas.classproperty
    def PACIFIC_CHATHAM(cls):
        return cls("Pacific/Chatham")
    
    @schemas.classproperty
    def PACIFIC_CHUUK(cls):
        return cls("Pacific/Chuuk")
    
    @schemas.classproperty
    def PACIFIC_EASTER(cls):
        return cls("Pacific/Easter")
    
    @schemas.classproperty
    def PACIFIC_EFATE(cls):
        return cls("Pacific/Efate")
    
    @schemas.classproperty
    def PACIFIC_ENDERBURY(cls):
        return cls("Pacific/Enderbury")
    
    @schemas.classproperty
    def PACIFIC_FAKAOFO(cls):
        return cls("Pacific/Fakaofo")
    
    @schemas.classproperty
    def PACIFIC_FIJI(cls):
        return cls("Pacific/Fiji")
    
    @schemas.classproperty
    def PACIFIC_FUNAFUTI(cls):
        return cls("Pacific/Funafuti")
    
    @schemas.classproperty
    def PACIFIC_GALAPAGOS(cls):
        return cls("Pacific/Galapagos")
    
    @schemas.classproperty
    def PACIFIC_GAMBIER(cls):
        return cls("Pacific/Gambier")
    
    @schemas.classproperty
    def PACIFIC_GUADALCANAL(cls):
        return cls("Pacific/Guadalcanal")
    
    @schemas.classproperty
    def PACIFIC_GUAM(cls):
        return cls("Pacific/Guam")
    
    @schemas.classproperty
    def PACIFIC_HONOLULU(cls):
        return cls("Pacific/Honolulu")
    
    @schemas.classproperty
    def PACIFIC_KIRITIMATI(cls):
        return cls("Pacific/Kiritimati")
    
    @schemas.classproperty
    def PACIFIC_KOSRAE(cls):
        return cls("Pacific/Kosrae")
    
    @schemas.classproperty
    def PACIFIC_KWAJALEIN(cls):
        return cls("Pacific/Kwajalein")
    
    @schemas.classproperty
    def PACIFIC_MAJURO(cls):
        return cls("Pacific/Majuro")
    
    @schemas.classproperty
    def PACIFIC_MARQUESAS(cls):
        return cls("Pacific/Marquesas")
    
    @schemas.classproperty
    def PACIFIC_MIDWAY(cls):
        return cls("Pacific/Midway")
    
    @schemas.classproperty
    def PACIFIC_NAURU(cls):
        return cls("Pacific/Nauru")
    
    @schemas.classproperty
    def PACIFIC_NIUE(cls):
        return cls("Pacific/Niue")
    
    @schemas.classproperty
    def PACIFIC_NORFOLK(cls):
        return cls("Pacific/Norfolk")
    
    @schemas.classproperty
    def PACIFIC_NOUMEA(cls):
        return cls("Pacific/Noumea")
    
    @schemas.classproperty
    def PACIFIC_PAGO_PAGO(cls):
        return cls("Pacific/Pago_Pago")
    
    @schemas.classproperty
    def PACIFIC_PALAU(cls):
        return cls("Pacific/Palau")
    
    @schemas.classproperty
    def PACIFIC_PITCAIRN(cls):
        return cls("Pacific/Pitcairn")
    
    @schemas.classproperty
    def PACIFIC_POHNPEI(cls):
        return cls("Pacific/Pohnpei")
    
    @schemas.classproperty
    def PACIFIC_PORT_MORESBY(cls):
        return cls("Pacific/Port_Moresby")
    
    @schemas.classproperty
    def PACIFIC_RAROTONGA(cls):
        return cls("Pacific/Rarotonga")
    
    @schemas.classproperty
    def PACIFIC_SAIPAN(cls):
        return cls("Pacific/Saipan")
    
    @schemas.classproperty
    def PACIFIC_TAHITI(cls):
        return cls("Pacific/Tahiti")
    
    @schemas.classproperty
    def PACIFIC_TARAWA(cls):
        return cls("Pacific/Tarawa")
    
    @schemas.classproperty
    def PACIFIC_TONGATAPU(cls):
        return cls("Pacific/Tongatapu")
    
    @schemas.classproperty
    def PACIFIC_WAKE(cls):
        return cls("Pacific/Wake")
    
    @schemas.classproperty
    def PACIFIC_WALLIS(cls):
        return cls("Pacific/Wallis")
    
    @schemas.classproperty
    def US_ALASKA(cls):
        return cls("US/Alaska")
    
    @schemas.classproperty
    def US_ARIZONA(cls):
        return cls("US/Arizona")
    
    @schemas.classproperty
    def US_CENTRAL(cls):
        return cls("US/Central")
    
    @schemas.classproperty
    def US_EASTERN(cls):
        return cls("US/Eastern")
    
    @schemas.classproperty
    def US_HAWAII(cls):
        return cls("US/Hawaii")
    
    @schemas.classproperty
    def US_MOUNTAIN(cls):
        return cls("US/Mountain")
    
    @schemas.classproperty
    def US_PACIFIC(cls):
        return cls("US/Pacific")
    
    @schemas.classproperty
    def UTC(cls):
        return cls("UTC")
