# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from procurify_python_sdk import schemas  # noqa: F401


class RequisitionLineCreateRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "unit",
            "quantity",
            "custom_fields",
            "account_code",
            "vendor_name",
            "item_name",
            "unit_price",
            "currency_code",
        }
        
        class properties:
            
            
            class item_name(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 255
                    min_length = 1
            
            
            class vendor_name(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    min_length = 1
            
            
            class account_code(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    min_length = 1
            
            
            class unit_price(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    format = 'decimal'
                    regex=[{
                        'pattern': r'^\d{0,13}(?:\.\d{0,8})?$',
                    }]
            
            
            class quantity(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    format = 'decimal'
                    regex=[{
                        'pattern': r'^\d{0,10}(?:\.\d{0,5})?$',
                    }]
            
            
            class unit(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 30
                    min_length = 1
            
            
            class currency_code(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    min_length = 1
            
            
            class custom_fields(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['LineItemCustomFieldRequest']:
                        return LineItemCustomFieldRequest
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['LineItemCustomFieldRequest'], typing.List['LineItemCustomFieldRequest']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'custom_fields':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'LineItemCustomFieldRequest':
                    return super().__getitem__(i)
            __annotations__ = {
                "item_name": item_name,
                "vendor_name": vendor_name,
                "account_code": account_code,
                "unit_price": unit_price,
                "quantity": quantity,
                "unit": unit,
                "currency_code": currency_code,
                "custom_fields": custom_fields,
            }
    
    unit: MetaOapg.properties.unit
    quantity: MetaOapg.properties.quantity
    custom_fields: MetaOapg.properties.custom_fields
    account_code: MetaOapg.properties.account_code
    vendor_name: MetaOapg.properties.vendor_name
    item_name: MetaOapg.properties.item_name
    unit_price: MetaOapg.properties.unit_price
    currency_code: MetaOapg.properties.currency_code
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["item_name"]) -> MetaOapg.properties.item_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vendor_name"]) -> MetaOapg.properties.vendor_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["account_code"]) -> MetaOapg.properties.account_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["unit_price"]) -> MetaOapg.properties.unit_price: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["quantity"]) -> MetaOapg.properties.quantity: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["unit"]) -> MetaOapg.properties.unit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency_code"]) -> MetaOapg.properties.currency_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["custom_fields"]) -> MetaOapg.properties.custom_fields: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["item_name", "vendor_name", "account_code", "unit_price", "quantity", "unit", "currency_code", "custom_fields", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["item_name"]) -> MetaOapg.properties.item_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vendor_name"]) -> MetaOapg.properties.vendor_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["account_code"]) -> MetaOapg.properties.account_code: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["unit_price"]) -> MetaOapg.properties.unit_price: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["quantity"]) -> MetaOapg.properties.quantity: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["unit"]) -> MetaOapg.properties.unit: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency_code"]) -> MetaOapg.properties.currency_code: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["custom_fields"]) -> MetaOapg.properties.custom_fields: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["item_name", "vendor_name", "account_code", "unit_price", "quantity", "unit", "currency_code", "custom_fields", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        unit: typing.Union[MetaOapg.properties.unit, str, ],
        quantity: typing.Union[MetaOapg.properties.quantity, str, ],
        custom_fields: typing.Union[MetaOapg.properties.custom_fields, list, tuple, ],
        account_code: typing.Union[MetaOapg.properties.account_code, str, ],
        vendor_name: typing.Union[MetaOapg.properties.vendor_name, str, ],
        item_name: typing.Union[MetaOapg.properties.item_name, str, ],
        unit_price: typing.Union[MetaOapg.properties.unit_price, str, ],
        currency_code: typing.Union[MetaOapg.properties.currency_code, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RequisitionLineCreateRequest':
        return super().__new__(
            cls,
            *args,
            unit=unit,
            quantity=quantity,
            custom_fields=custom_fields,
            account_code=account_code,
            vendor_name=vendor_name,
            item_name=item_name,
            unit_price=unit_price,
            currency_code=currency_code,
            _configuration=_configuration,
            **kwargs,
        )

from procurify_python_sdk.model.line_item_custom_field_request import LineItemCustomFieldRequest
