# coding: utf-8

"""
    Procurify API Documentation

     # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 

    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from procurify_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from procurify_python_sdk.api_response import AsyncGeneratorResponse
from procurify_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from procurify_python_sdk import schemas  # noqa: F401

from procurify_python_sdk.model.paginated_order_read_list import PaginatedOrderReadList as PaginatedOrderReadListSchema

from procurify_python_sdk.type.paginated_order_read_list import PaginatedOrderReadList

from ...api_client import Dictionary
from procurify_python_sdk.pydantic.paginated_order_read_list import PaginatedOrderReadList as PaginatedOrderReadListPydantic

# Query params
BranchSchema = schemas.IntSchema
DateRequiredSchema = schemas.DateTimeSchema
Date0Schema = schemas.DateSchema
Date1Schema = schemas.DateSchema
DepartmentSchema = schemas.IntSchema


class FormatSchema(
    schemas.EnumBase,
    schemas.StrSchema
):
    
    @schemas.classproperty
    def CSV(cls):
        return cls("csv")
    
    @schemas.classproperty
    def JSON(cls):
        return cls("json")
HasBlanketOrderItemsSchema = schemas.BoolSchema
IsPunchoutSchema = schemas.BoolSchema
LineCountSchema = schemas.IntSchema
LocationSchema = schemas.IntSchema
ModifiedDate0Schema = schemas.DateSchema
ModifiedDate1Schema = schemas.DateSchema
OrderBySchema = schemas.StrSchema
PageSchema = schemas.IntSchema
PageSizeSchema = schemas.IntSchema
RequiredDate0Schema = schemas.DateSchema
RequiredDate1Schema = schemas.DateSchema
SearchSchema = schemas.StrSchema


class StatusSchema(
    schemas.EnumBase,
    schemas.IntSchema
):
    
    @schemas.classproperty
    def POSITIVE_0(cls):
        return cls(0)
    
    @schemas.classproperty
    def POSITIVE_1(cls):
        return cls(1)
    
    @schemas.classproperty
    def POSITIVE_2(cls):
        return cls(2)
    
    @schemas.classproperty
    def POSITIVE_3(cls):
        return cls(3)
    
    @schemas.classproperty
    def POSITIVE_4(cls):
        return cls(4)
    
    @schemas.classproperty
    def POSITIVE_5(cls):
        return cls(5)
    
    @schemas.classproperty
    def POSITIVE_6(cls):
        return cls(6)
TotalPriceSchema = schemas.NumberSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'branch': typing.Union[BranchSchema, decimal.Decimal, int, ],
        'dateRequired': typing.Union[DateRequiredSchema, str, datetime, ],
        'date_0': typing.Union[Date0Schema, str, date, ],
        'date_1': typing.Union[Date1Schema, str, date, ],
        'department': typing.Union[DepartmentSchema, decimal.Decimal, int, ],
        'format': typing.Union[FormatSchema, str, ],
        'has_blanket_order_items': typing.Union[HasBlanketOrderItemsSchema, bool, ],
        'is_punchout': typing.Union[IsPunchoutSchema, bool, ],
        'lineCount': typing.Union[LineCountSchema, decimal.Decimal, int, ],
        'location': typing.Union[LocationSchema, decimal.Decimal, int, ],
        'modified_date_0': typing.Union[ModifiedDate0Schema, str, date, ],
        'modified_date_1': typing.Union[ModifiedDate1Schema, str, date, ],
        'order_by': typing.Union[OrderBySchema, str, ],
        'page': typing.Union[PageSchema, decimal.Decimal, int, ],
        'page_size': typing.Union[PageSizeSchema, decimal.Decimal, int, ],
        'required_date_0': typing.Union[RequiredDate0Schema, str, date, ],
        'required_date_1': typing.Union[RequiredDate1Schema, str, date, ],
        'search': typing.Union[SearchSchema, str, ],
        'status': typing.Union[StatusSchema, decimal.Decimal, int, ],
        'totalPrice': typing.Union[TotalPriceSchema, decimal.Decimal, int, float, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_branch = api_client.QueryParameter(
    name="branch",
    style=api_client.ParameterStyle.FORM,
    schema=BranchSchema,
    explode=True,
)
request_query_date_required = api_client.QueryParameter(
    name="dateRequired",
    style=api_client.ParameterStyle.FORM,
    schema=DateRequiredSchema,
    explode=True,
)
request_query_date_0 = api_client.QueryParameter(
    name="date_0",
    style=api_client.ParameterStyle.FORM,
    schema=Date0Schema,
    explode=True,
)
request_query_date_1 = api_client.QueryParameter(
    name="date_1",
    style=api_client.ParameterStyle.FORM,
    schema=Date1Schema,
    explode=True,
)
request_query_department = api_client.QueryParameter(
    name="department",
    style=api_client.ParameterStyle.FORM,
    schema=DepartmentSchema,
    explode=True,
)
request_query_format = api_client.QueryParameter(
    name="format",
    style=api_client.ParameterStyle.FORM,
    schema=FormatSchema,
    explode=True,
)
request_query_has_blanket_order_items = api_client.QueryParameter(
    name="has_blanket_order_items",
    style=api_client.ParameterStyle.FORM,
    schema=HasBlanketOrderItemsSchema,
    explode=True,
)
request_query_is_punchout = api_client.QueryParameter(
    name="is_punchout",
    style=api_client.ParameterStyle.FORM,
    schema=IsPunchoutSchema,
    explode=True,
)
request_query_line_count = api_client.QueryParameter(
    name="lineCount",
    style=api_client.ParameterStyle.FORM,
    schema=LineCountSchema,
    explode=True,
)
request_query_location = api_client.QueryParameter(
    name="location",
    style=api_client.ParameterStyle.FORM,
    schema=LocationSchema,
    explode=True,
)
request_query_modified_date_0 = api_client.QueryParameter(
    name="modified_date_0",
    style=api_client.ParameterStyle.FORM,
    schema=ModifiedDate0Schema,
    explode=True,
)
request_query_modified_date_1 = api_client.QueryParameter(
    name="modified_date_1",
    style=api_client.ParameterStyle.FORM,
    schema=ModifiedDate1Schema,
    explode=True,
)
request_query_order_by = api_client.QueryParameter(
    name="order_by",
    style=api_client.ParameterStyle.FORM,
    schema=OrderBySchema,
    explode=True,
)
request_query_page = api_client.QueryParameter(
    name="page",
    style=api_client.ParameterStyle.FORM,
    schema=PageSchema,
    explode=True,
)
request_query_page_size = api_client.QueryParameter(
    name="page_size",
    style=api_client.ParameterStyle.FORM,
    schema=PageSizeSchema,
    explode=True,
)
request_query_required_date_0 = api_client.QueryParameter(
    name="required_date_0",
    style=api_client.ParameterStyle.FORM,
    schema=RequiredDate0Schema,
    explode=True,
)
request_query_required_date_1 = api_client.QueryParameter(
    name="required_date_1",
    style=api_client.ParameterStyle.FORM,
    schema=RequiredDate1Schema,
    explode=True,
)
request_query_search = api_client.QueryParameter(
    name="search",
    style=api_client.ParameterStyle.FORM,
    schema=SearchSchema,
    explode=True,
)
request_query_status = api_client.QueryParameter(
    name="status",
    style=api_client.ParameterStyle.FORM,
    schema=StatusSchema,
    explode=True,
)
request_query_total_price = api_client.QueryParameter(
    name="totalPrice",
    style=api_client.ParameterStyle.FORM,
    schema=TotalPriceSchema,
    explode=True,
)
SchemaFor200ResponseBodyApplicationJson = PaginatedOrderReadListSchema
SchemaFor200ResponseBodyTextCsv = PaginatedOrderReadListSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: PaginatedOrderReadList


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: PaginatedOrderReadList


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
        'text/csv': api_client.MediaType(
            schema=SchemaFor200ResponseBodyTextCsv),
    },
)
_all_accept_content_types = (
    'application/json',
    'text/csv',
)


class BaseApi(api_client.Api):

    def _get_all_orders_mapped_args(
        self,
        branch: typing.Optional[int] = None,
        date_required: typing.Optional[datetime] = None,
        date_0: typing.Optional[date] = None,
        date_1: typing.Optional[date] = None,
        department: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        has_blanket_order_items: typing.Optional[bool] = None,
        is_punchout: typing.Optional[bool] = None,
        line_count: typing.Optional[int] = None,
        location: typing.Optional[int] = None,
        modified_date_0: typing.Optional[date] = None,
        modified_date_1: typing.Optional[date] = None,
        order_by: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        required_date_0: typing.Optional[date] = None,
        required_date_1: typing.Optional[date] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[int] = None,
        total_price: typing.Optional[typing.Union[int, float]] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if branch is not None:
            _query_params["branch"] = branch
        if date_required is not None:
            _query_params["dateRequired"] = date_required
        if date_0 is not None:
            _query_params["date_0"] = date_0
        if date_1 is not None:
            _query_params["date_1"] = date_1
        if department is not None:
            _query_params["department"] = department
        if format is not None:
            _query_params["format"] = format
        if has_blanket_order_items is not None:
            _query_params["has_blanket_order_items"] = has_blanket_order_items
        if is_punchout is not None:
            _query_params["is_punchout"] = is_punchout
        if line_count is not None:
            _query_params["lineCount"] = line_count
        if location is not None:
            _query_params["location"] = location
        if modified_date_0 is not None:
            _query_params["modified_date_0"] = modified_date_0
        if modified_date_1 is not None:
            _query_params["modified_date_1"] = modified_date_1
        if order_by is not None:
            _query_params["order_by"] = order_by
        if page is not None:
            _query_params["page"] = page
        if page_size is not None:
            _query_params["page_size"] = page_size
        if required_date_0 is not None:
            _query_params["required_date_0"] = required_date_0
        if required_date_1 is not None:
            _query_params["required_date_1"] = required_date_1
        if search is not None:
            _query_params["search"] = search
        if status is not None:
            _query_params["status"] = status
        if total_price is not None:
            _query_params["totalPrice"] = total_price
        args.query = _query_params
        return args

    async def _aget_all_orders_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Get All Orders
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_branch,
            request_query_date_required,
            request_query_date_0,
            request_query_date_1,
            request_query_department,
            request_query_format,
            request_query_has_blanket_order_items,
            request_query_is_punchout,
            request_query_line_count,
            request_query_location,
            request_query_modified_date_0,
            request_query_modified_date_1,
            request_query_order_by,
            request_query_page,
            request_query_page_size,
            request_query_required_date_0,
            request_query_required_date_1,
            request_query_search,
            request_query_status,
            request_query_total_price,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/api/v2/global/orders',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_all_orders_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Get All Orders
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_branch,
            request_query_date_required,
            request_query_date_0,
            request_query_date_1,
            request_query_department,
            request_query_format,
            request_query_has_blanket_order_items,
            request_query_is_punchout,
            request_query_line_count,
            request_query_location,
            request_query_modified_date_0,
            request_query_modified_date_1,
            request_query_order_by,
            request_query_page,
            request_query_page_size,
            request_query_required_date_0,
            request_query_required_date_1,
            request_query_search,
            request_query_status,
            request_query_total_price,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/api/v2/global/orders',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetAllOrdersRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_all_orders(
        self,
        branch: typing.Optional[int] = None,
        date_required: typing.Optional[datetime] = None,
        date_0: typing.Optional[date] = None,
        date_1: typing.Optional[date] = None,
        department: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        has_blanket_order_items: typing.Optional[bool] = None,
        is_punchout: typing.Optional[bool] = None,
        line_count: typing.Optional[int] = None,
        location: typing.Optional[int] = None,
        modified_date_0: typing.Optional[date] = None,
        modified_date_1: typing.Optional[date] = None,
        order_by: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        required_date_0: typing.Optional[date] = None,
        required_date_1: typing.Optional[date] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[int] = None,
        total_price: typing.Optional[typing.Union[int, float]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_all_orders_mapped_args(
            branch=branch,
            date_required=date_required,
            date_0=date_0,
            date_1=date_1,
            department=department,
            format=format,
            has_blanket_order_items=has_blanket_order_items,
            is_punchout=is_punchout,
            line_count=line_count,
            location=location,
            modified_date_0=modified_date_0,
            modified_date_1=modified_date_1,
            order_by=order_by,
            page=page,
            page_size=page_size,
            required_date_0=required_date_0,
            required_date_1=required_date_1,
            search=search,
            status=status,
            total_price=total_price,
        )
        return await self._aget_all_orders_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get_all_orders(
        self,
        branch: typing.Optional[int] = None,
        date_required: typing.Optional[datetime] = None,
        date_0: typing.Optional[date] = None,
        date_1: typing.Optional[date] = None,
        department: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        has_blanket_order_items: typing.Optional[bool] = None,
        is_punchout: typing.Optional[bool] = None,
        line_count: typing.Optional[int] = None,
        location: typing.Optional[int] = None,
        modified_date_0: typing.Optional[date] = None,
        modified_date_1: typing.Optional[date] = None,
        order_by: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        required_date_0: typing.Optional[date] = None,
        required_date_1: typing.Optional[date] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[int] = None,
        total_price: typing.Optional[typing.Union[int, float]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_all_orders_mapped_args(
            branch=branch,
            date_required=date_required,
            date_0=date_0,
            date_1=date_1,
            department=department,
            format=format,
            has_blanket_order_items=has_blanket_order_items,
            is_punchout=is_punchout,
            line_count=line_count,
            location=location,
            modified_date_0=modified_date_0,
            modified_date_1=modified_date_1,
            order_by=order_by,
            page=page,
            page_size=page_size,
            required_date_0=required_date_0,
            required_date_1=required_date_1,
            search=search,
            status=status,
            total_price=total_price,
        )
        return self._get_all_orders_oapg(
            query_params=args.query,
        )

class GetAllOrders(BaseApi):

    async def aget_all_orders(
        self,
        branch: typing.Optional[int] = None,
        date_required: typing.Optional[datetime] = None,
        date_0: typing.Optional[date] = None,
        date_1: typing.Optional[date] = None,
        department: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        has_blanket_order_items: typing.Optional[bool] = None,
        is_punchout: typing.Optional[bool] = None,
        line_count: typing.Optional[int] = None,
        location: typing.Optional[int] = None,
        modified_date_0: typing.Optional[date] = None,
        modified_date_1: typing.Optional[date] = None,
        order_by: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        required_date_0: typing.Optional[date] = None,
        required_date_1: typing.Optional[date] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[int] = None,
        total_price: typing.Optional[typing.Union[int, float]] = None,
        validate: bool = False,
        **kwargs,
    ) -> PaginatedOrderReadListPydantic:
        raw_response = await self.raw.aget_all_orders(
            branch=branch,
            date_required=date_required,
            date_0=date_0,
            date_1=date_1,
            department=department,
            format=format,
            has_blanket_order_items=has_blanket_order_items,
            is_punchout=is_punchout,
            line_count=line_count,
            location=location,
            modified_date_0=modified_date_0,
            modified_date_1=modified_date_1,
            order_by=order_by,
            page=page,
            page_size=page_size,
            required_date_0=required_date_0,
            required_date_1=required_date_1,
            search=search,
            status=status,
            total_price=total_price,
            **kwargs,
        )
        if validate:
            return PaginatedOrderReadListPydantic(**raw_response.body)
        return api_client.construct_model_instance(PaginatedOrderReadListPydantic, raw_response.body)
    
    
    def get_all_orders(
        self,
        branch: typing.Optional[int] = None,
        date_required: typing.Optional[datetime] = None,
        date_0: typing.Optional[date] = None,
        date_1: typing.Optional[date] = None,
        department: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        has_blanket_order_items: typing.Optional[bool] = None,
        is_punchout: typing.Optional[bool] = None,
        line_count: typing.Optional[int] = None,
        location: typing.Optional[int] = None,
        modified_date_0: typing.Optional[date] = None,
        modified_date_1: typing.Optional[date] = None,
        order_by: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        required_date_0: typing.Optional[date] = None,
        required_date_1: typing.Optional[date] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[int] = None,
        total_price: typing.Optional[typing.Union[int, float]] = None,
        validate: bool = False,
    ) -> PaginatedOrderReadListPydantic:
        raw_response = self.raw.get_all_orders(
            branch=branch,
            date_required=date_required,
            date_0=date_0,
            date_1=date_1,
            department=department,
            format=format,
            has_blanket_order_items=has_blanket_order_items,
            is_punchout=is_punchout,
            line_count=line_count,
            location=location,
            modified_date_0=modified_date_0,
            modified_date_1=modified_date_1,
            order_by=order_by,
            page=page,
            page_size=page_size,
            required_date_0=required_date_0,
            required_date_1=required_date_1,
            search=search,
            status=status,
            total_price=total_price,
        )
        if validate:
            return PaginatedOrderReadListPydantic(**raw_response.body)
        return api_client.construct_model_instance(PaginatedOrderReadListPydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        branch: typing.Optional[int] = None,
        date_required: typing.Optional[datetime] = None,
        date_0: typing.Optional[date] = None,
        date_1: typing.Optional[date] = None,
        department: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        has_blanket_order_items: typing.Optional[bool] = None,
        is_punchout: typing.Optional[bool] = None,
        line_count: typing.Optional[int] = None,
        location: typing.Optional[int] = None,
        modified_date_0: typing.Optional[date] = None,
        modified_date_1: typing.Optional[date] = None,
        order_by: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        required_date_0: typing.Optional[date] = None,
        required_date_1: typing.Optional[date] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[int] = None,
        total_price: typing.Optional[typing.Union[int, float]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_all_orders_mapped_args(
            branch=branch,
            date_required=date_required,
            date_0=date_0,
            date_1=date_1,
            department=department,
            format=format,
            has_blanket_order_items=has_blanket_order_items,
            is_punchout=is_punchout,
            line_count=line_count,
            location=location,
            modified_date_0=modified_date_0,
            modified_date_1=modified_date_1,
            order_by=order_by,
            page=page,
            page_size=page_size,
            required_date_0=required_date_0,
            required_date_1=required_date_1,
            search=search,
            status=status,
            total_price=total_price,
        )
        return await self._aget_all_orders_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        branch: typing.Optional[int] = None,
        date_required: typing.Optional[datetime] = None,
        date_0: typing.Optional[date] = None,
        date_1: typing.Optional[date] = None,
        department: typing.Optional[int] = None,
        format: typing.Optional[str] = None,
        has_blanket_order_items: typing.Optional[bool] = None,
        is_punchout: typing.Optional[bool] = None,
        line_count: typing.Optional[int] = None,
        location: typing.Optional[int] = None,
        modified_date_0: typing.Optional[date] = None,
        modified_date_1: typing.Optional[date] = None,
        order_by: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        required_date_0: typing.Optional[date] = None,
        required_date_1: typing.Optional[date] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[int] = None,
        total_price: typing.Optional[typing.Union[int, float]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_all_orders_mapped_args(
            branch=branch,
            date_required=date_required,
            date_0=date_0,
            date_1=date_1,
            department=department,
            format=format,
            has_blanket_order_items=has_blanket_order_items,
            is_punchout=is_punchout,
            line_count=line_count,
            location=location,
            modified_date_0=modified_date_0,
            modified_date_1=modified_date_1,
            order_by=order_by,
            page=page,
            page_size=page_size,
            required_date_0=required_date_0,
            required_date_1=required_date_1,
            search=search,
            status=status,
            total_price=total_price,
        )
        return self._get_all_orders_oapg(
            query_params=args.query,
        )

